#!/usr/bin/env python3
"""Pixel authority gate for the AW-011 Camera Corridor.

This module intentionally knows nothing about diffusion, scaffold providers, or
image file formats. It enforces the authority boundary after those systems run:
known world bytes are immutable; generated bytes may enter only through unseen
mask positions; the canonical return pose is replaced by the exact source.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class GateReport:
    pixel_count: int
    known_pixel_count: int
    unseen_pixel_count: int
    known_byte_delta_count: int

    @property
    def known_pixels_preserved(self) -> bool:
        return self.known_byte_delta_count == 0


def _validate_buffers(known: bytes, generated: bytes, unseen_mask: bytes, channels: int) -> int:
    if channels <= 0:
        raise ValueError("channels must be positive")
    if len(known) != len(generated):
        raise ValueError("known and generated buffers must have identical length")
    if len(known) % channels:
        raise ValueError("pixel buffers are not divisible by channel count")
    pixel_count = len(known) // channels
    if len(unseen_mask) != pixel_count:
        raise ValueError("unseen_mask must contain exactly one byte per pixel")
    if any(value not in (0, 1) for value in unseen_mask):
        raise ValueError("unseen_mask values must be 0 or 1")
    return pixel_count


def compose_unseen_only(
    known: bytes,
    generated: bytes,
    unseen_mask: bytes,
    *,
    channels: int = 4,
) -> tuple[bytes, GateReport]:
    """Composite generated pixels only where unseen_mask is 1.

    `known` is the authoritative reprojected corridor image. The generated image
    can never repaint a known pixel through this function.
    """

    pixel_count = _validate_buffers(known, generated, unseen_mask, channels)
    output = bytearray(known)

    unseen_pixel_count = 0
    for pixel_index, is_unseen in enumerate(unseen_mask):
        if not is_unseen:
            continue
        unseen_pixel_count += 1
        start = pixel_index * channels
        end = start + channels
        output[start:end] = generated[start:end]

    output_bytes = bytes(output)
    known_byte_delta_count = 0
    for pixel_index, is_unseen in enumerate(unseen_mask):
        if is_unseen:
            continue
        start = pixel_index * channels
        end = start + channels
        for before, after in zip(known[start:end], output_bytes[start:end]):
            if before != after:
                known_byte_delta_count += 1

    report = GateReport(
        pixel_count=pixel_count,
        known_pixel_count=pixel_count - unseen_pixel_count,
        unseen_pixel_count=unseen_pixel_count,
        known_byte_delta_count=known_byte_delta_count,
    )
    return output_bytes, report


def hard_source_relock(
    rendered: bytes,
    source: bytes,
    *,
    pose_id: str,
    canonical_pose_id: str = "P000",
) -> bytes:
    """Return exact source bytes whenever the camera is at the canonical pose."""

    if len(rendered) != len(source):
        raise ValueError("rendered and source buffers must have identical length")
    return source if pose_id == canonical_pose_id else rendered


def exact_relock_passes(frame: bytes, source: bytes) -> bool:
    return frame == source
