/* DORÉ Companion 2.0: normal ChatGPT conversation -> Native Messaging -> DORÉ. */
const BADGE_ID="dore-a2a-companion-status",TERMINAL_HOLD_MS=30000;let lastCommand="",lastCommandAt=0,healthTimer=null,pendingComposerCommand="",commandInFlight=false,terminalHoldUntil=0;const seenMessageNodes=new WeakSet(),seenDirectives=new Set();
function ensureBadge(){let b=document.getElementById(BADGE_ID);if(b)return b;b=document.createElement("div");b.id=BADGE_ID;b.setAttribute("role","status");b.style.cssText="position:fixed;right:14px;bottom:14px;z-index:2147483647;padding:6px 9px;border-radius:999px;font:600 11px/1.2 -apple-system,sans-serif;background:rgba(20,20,20,.88);color:#d7bd72;border:1px solid rgba(215,189,114,.55);pointer-events:none";document.documentElement.appendChild(b);return b}
function setBadge(s,d,h=false){const b=ensureBadge(),n=String(s||"OFFLINE").toUpperCase();b.textContent=`DORÉ A2A · ${n}`;b.title=d||"";if(h)terminalHoldUntil=Date.now()+TERMINAL_HOLD_MS}
async function refreshHealth(){if(commandInFlight||Date.now()<terminalHoldUntil)return;try{const r=await browser.runtime.sendMessage({type:"dore.health"});setBadge(r&&r.online?"ONLINE":"OFFLINE",r&&r.transport||r&&r.error||"")}catch(e){setBadge("OFFLINE",String(e))}}
function readNode(n){if(!n)return"";if(n instanceof HTMLTextAreaElement||n instanceof HTMLInputElement)return n.value||"";return n.innerText||n.textContent||""}
function composerRoot(){return document.querySelector('#prompt-textarea')||document.querySelector('[data-testid="composer-text-input"]')||document.querySelector('form textarea')||document.querySelector('form [contenteditable="true"]')}
function normalizeCommand(raw){const t=String(raw||"").replace(/\u00a0/g," ").trim();return t.toLowerCase().startsWith("/dore")?t:""}
function currentComposerCommand(){return normalizeCommand(readNode(composerRoot()))}
function conversationId(){const m=location.pathname.match(/\/c\/([^/?#]+)/);return m?`chatgpt:${m[1]}`:`chatgpt:${location.pathname}`}
function resultDetail(r){return JSON.stringify(r||{})}
async function dispatchCommand(raw,source="composer"){const command=normalizeCommand(raw);if(!command)return;const now=Date.now();if(command===lastCommand&&now-lastCommandAt<2500)return;lastCommand=command;lastCommandAt=now;commandInFlight=true;setBadge("SENT",command);try{const reply=await browser.runtime.sendMessage({type:"dore.command",command,source,conversation_id:conversationId()});if(reply&&reply.ok&&reply.result){setBadge(reply.result.ok===false?"FAILED":"PASS",resultDetail(reply.result),true)}else setBadge("ERROR",reply&&reply.error||"failed",true)}finally{commandInFlight=false}}
function rememberComposer(){const c=currentComposerCommand();if(c){pendingComposerCommand=c;setBadge("CAPTURED",c)}}
function parseDirectives(text){const out=[],re=/\[\[DORE_DIRECTIVE\s+({[\s\S]*?})\s*\]\]/g;let m;while((m=re.exec(text))){try{const p=JSON.parse(m[1]);if(p&&typeof p.capability==="string")out.push(p)}catch(_){}}return out}
function directiveKey(p){return String(p.request_id||`${p.capability}:${JSON.stringify(p.args||{})}`)}
function setComposerText(text){const el=composerRoot();if(!el)return false;el.focus();if(el instanceof HTMLTextAreaElement||el instanceof HTMLInputElement){const setter=Object.getOwnPropertyDescriptor(Object.getPrototypeOf(el),"value")?.set;setter?setter.call(el,text):el.value=text}else{el.textContent=text}el.dispatchEvent(new InputEvent("input",{bubbles:true,inputType:"insertText",data:text}));return true}
function submitComposer(){const btn=document.querySelector('button[data-testid="send-button"]')||document.querySelector('button[aria-label*="Send" i]');if(btn&&!btn.disabled){btn.click();return true}const el=composerRoot();if(el){el.dispatchEvent(new KeyboardEvent("keydown",{key:"Enter",code:"Enter",bubbles:true,cancelable:true}));return true}return false}
async function returnResult(p,result){const envelope=`[DORÉ_LOCAL_RESULT ${JSON.stringify({request_id:p.request_id||null,capability:p.capability,result})}]`;if(!setComposerText(envelope)){setBadge("ERROR","cannot return local result",true);return}await new Promise(r=>setTimeout(r,80));submitComposer()}
async function executeDirective(p){const key=directiveKey(p);if(seenDirectives.has(key))return;seenDirectives.add(key);commandInFlight=true;setBadge("EXEC",p.capability);try{const reply=await browser.runtime.sendMessage({type:"dore.directive",directive:p,conversation_id:conversationId()});const result=reply&&reply.result?reply.result:{ok:false,error:reply&&reply.error||"directive failed"};setBadge(result.ok?"PASS":"FAILED",resultDetail(result),true);await returnResult(p,result)}catch(e){const result={ok:false,error:String(e&&e.message||e)};setBadge("ERROR",result.error,true);await returnResult(p,result)}finally{commandInFlight=false}}
function scanAssistant(root){const nodes=[];if(root instanceof Element&&root.matches('[data-message-author-role="assistant"]'))nodes.push(root);if(root instanceof Element)nodes.push(...root.querySelectorAll('[data-message-author-role="assistant"]'));for(const n of nodes)for(const p of parseDirectives(readNode(n)))executeDirective(p)}
function observeMessages(){document.querySelectorAll('[data-message-author-role="user"]').forEach(n=>seenMessageNodes.add(n));document.querySelectorAll('[data-message-author-role="assistant"]').forEach(scanAssistant);const o=new MutationObserver(ms=>{for(const m of ms)for(const n of m.addedNodes){scanAssistant(n);if(!(n instanceof Element))continue;const users=[];if(n.matches('[data-message-author-role="user"]'))users.push(n);users.push(...n.querySelectorAll('[data-message-author-role="user"]'));for(const u of users){if(seenMessageNodes.has(u))continue;seenMessageNodes.add(u);const c=normalizeCommand(readNode(u));if(c)dispatchCommand(c,"submitted-message")}}});o.observe(document.documentElement,{childList:true,subtree:true});return o}
document.addEventListener("input",rememberComposer,true);document.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){const c=currentComposerCommand()||pendingComposerCommand;if(c)dispatchCommand(c,"keydown")}},true);ensureBadge();const observer=observeMessages();refreshHealth();healthTimer=setInterval(refreshHealth,10000);window.addEventListener("beforeunload",()=>{clearInterval(healthTimer);observer.disconnect()},{once:true});
