/* Runtime source-probe bridge. Keeps provider handling out of product surfaces. */
let runtimeTransportPromise=null;
function runtimeTransport(){if(!runtimeTransportPromise)runtimeTransportPromise=import(browser.runtime.getURL('native_transport.js'));return runtimeTransportPromise;}
function sleep(ms){return new Promise(resolve=>setTimeout(resolve,ms));}
async function waitReady(tabId,timeout=20000){const start=Date.now();while(Date.now()-start<timeout){const tab=await browser.tabs.get(tabId);if(tab.status==='complete')return;await sleep(200);}throw new Error('runtime probe load timeout');}
const SNAPSHOT_CODE=`(()=>{const abs=v=>{if(!v)return null;try{return new URL(v,document.baseURI).href}catch(_){return String(v)}};const videos=[...document.querySelectorAll('video')].map(n=>({src:abs(n.getAttribute('src')),currentSrc:abs(n.currentSrc),poster:abs(n.poster||n.getAttribute('poster')),type:n.getAttribute('type')||null,duration:Number.isFinite(n.duration)?n.duration:null}));const sources=[...document.querySelectorAll('source')].map(n=>({src:abs(n.src||n.getAttribute('src')),type:n.type||n.getAttribute('type')||null}));const tracks=[...document.querySelectorAll('track')].map(n=>({src:abs(n.src||n.getAttribute('src')),kind:n.kind||n.getAttribute('kind')||null,srclang:n.srclang||n.getAttribute('srclang')||null,label:n.label||null}));const iframes=[...document.querySelectorAll('iframe')].map(n=>({src:abs(n.src||n.getAttribute('src')),title:n.title||null}));const images=[...document.images].map(n=>{const text=[n.alt,n.title,n.className,n.id,n.getAttribute('aria-label')].filter(Boolean).join(' ').toLowerCase();const role=/poster|thumbnail|thumb|hero|video/.test(text)?(/poster/.test(text)?'poster':/hero/.test(text)?'hero':'thumbnail'):null;return {src:abs(n.currentSrc||n.src),role,videoRelated:Boolean(role),width:n.naturalWidth||null,height:n.naturalHeight||null}}).filter(x=>x.src);const resources=performance.getEntriesByType?performance.getEntriesByType('resource').map(e=>({name:e.name,initiatorType:e.initiatorType||null,duration:e.duration||null})):[];return {schema:'dore.runtime-source-probe.v0',collector:'dore.runtime-source-probe.v0',url:location.href,identity:{title:document.querySelector('meta[property="og:title"]')?.content||document.title||null,creator:document.querySelector('meta[name="author"]')?.content||null,duration:videos.map(v=>v.duration).find(Number.isFinite)??null},videos,sources,tracks,iframes,images,resources,reflexPersistent:false,probeAuthority:false,rights:{rehost:false}}})()`;
async function nativeProbe(url,args){const transport=await runtimeTransport();return transport.sendDorePayload({capability:'source.probe',args,caller_product:'cinema',source:'westsidewatch-runtime-source-probe',client:{name:'dore-companion',version:'2.0.0'}});}
async function collect(url){let tab;try{tab=await browser.tabs.create({url,active:false});await waitReady(tab.id);await sleep(1500);const out=await browser.tabs.executeScript(tab.id,{code:SNAPSHOT_CODE,runAt:'document_idle'});const snapshot=Array.isArray(out)?out.find(x=>x&&typeof x==='object'):null;if(!snapshot)throw new Error('runtime probe produced no evidence');return snapshot;}finally{if(tab?.id!=null){try{await browser.tabs.remove(tab.id)}catch(_){}}}}
async function run(url){const initial=await nativeProbe(url,{url,allowNetwork:true});const needs=Array.isArray(initial?.needs)?initial.needs:[];const posters=initial?.capabilities?.poster;if(!needs.includes('runtime-browser-probe')&&Array.isArray(posters)&&posters.length)return initial;const snapshot=await collect(url);return nativeProbe(url,{url,runtimeSnapshot:snapshot});}
browser.runtime.onMessage.addListener(message=>{if(!message||message.type!=='dore.runtime-source-probe')return undefined;const url=String(message.url||'').trim();if(!url)return Promise.resolve({ok:false,error:'url required'});return run(url).then(result=>({ok:Boolean(result&&result.ok),result})).catch(error=>({ok:false,error:String(error&&error.message||error)}));});
