/* Runtime source-probe bridge. Keeps provider handling out of product surfaces. */
const SOURCE_DISPATCH_SCHEMA='dore.source-dispatch.v1';
let runtimeTransportPromise=null;
function runtimeTransport(){if(!runtimeTransportPromise)runtimeTransportPromise=import(browser.runtime.getURL('native_transport.js'));return runtimeTransportPromise;}
function sleep(ms){return new Promise(resolve=>setTimeout(resolve,ms));}
async function waitReady(tabId,timeout=20000){const started=Date.now();while(Date.now()-started<timeout){const tab=await browser.tabs.get(tabId);if(tab.status==='complete')return;await sleep(200);}throw new Error('runtime probe load timeout');}
const SNAPSHOT_CODE=`(()=>{const abs=v=>{if(!v)return null;try{return new URL(v,document.baseURI).href}catch(_){return String(v)}};const videos=[...document.querySelectorAll('video')].map(n=>({src:abs(n.getAttribute('src')),currentSrc:abs(n.currentSrc),poster:abs(n.poster||n.getAttribute('poster')),type:n.getAttribute('type')||null,duration:Number.isFinite(n.duration)?n.duration:null}));const sources=[...document.querySelectorAll('source')].map(n=>({src:abs(n.src||n.getAttribute('src')),type:n.type||n.getAttribute('type')||null}));const tracks=[...document.querySelectorAll('track')].map(n=>({src:abs(n.src||n.getAttribute('src')),kind:n.kind||n.getAttribute('kind')||null,srclang:n.srclang||n.getAttribute('srclang')||null,label:n.label||null}));const iframes=[...document.querySelectorAll('iframe')].map(n=>({src:abs(n.src||n.getAttribute('src')),title:n.title||null}));const images=[...document.images].map(n=>{const text=[n.alt,n.title,n.className,n.id,n.getAttribute('aria-label')].filter(Boolean).join(' ').toLowerCase();const role=/poster|thumbnail|thumb|hero|video/.test(text)?(/poster/.test(text)?'poster':/hero/.test(text)?'hero':'thumbnail'):null;return {src:abs(n.currentSrc||n.src),role,videoRelated:Boolean(role),width:n.naturalWidth||null,height:n.naturalHeight||null}}).filter(x=>x.src);const resources=performance.getEntriesByType?performance.getEntriesByType('resource').map(e=>({name:e.name,initiatorType:e.initiatorType||null,duration:e.duration||null})):[];return {schema:'dore.runtime-source-probe.v0',collector:'dore.runtime-source-probe.v0',url:location.href,identity:{title:document.querySelector('meta[property="og:title"]')?.content||document.title||null,creator:document.querySelector('meta[name="author"]')?.content||null,duration:videos.map(v=>v.duration).find(Number.isFinite)??null},videos,sources,tracks,iframes,images,resources,reflexPersistent:false,probeAuthority:false,rights:{rehost:false}}})()`;
async function nativeCall(capability,args){const transport=await runtimeTransport();return transport.sendDorePayload({capability,args,caller_product:'cinema',source:'westsidewatch-runtime-source-probe',client:{name:'dore-companion',version:'2.0.0'}});}
async function nativeProbe(url,args){return nativeCall('source.probe',args);}
async function capabilityEnvelope(probe){return nativeCall('source.capability-envelope',{probe});}
function sourceDispatch(envelope){const dispatch=envelope?.dispatch||null;return dispatch?.schema===SOURCE_DISPATCH_SCHEMA&&dispatch?.ok===true?dispatch:null;}
async function collect(url){let tab;try{tab=await browser.tabs.create({url,active:false});await waitReady(tab.id);await sleep(1500);const out=await browser.tabs.executeScript(tab.id,{code:SNAPSHOT_CODE,runAt:'document_idle'});const snapshot=Array.isArray(out)?out.find(x=>x&&typeof x==='object'):null;if(!snapshot)throw new Error('runtime probe produced no evidence');return snapshot;}finally{if(tab?.id!=null){try{await browser.tabs.remove(tab.id)}catch(_){}}}}
async function attachEnvelope(probe){const envelope=await capabilityEnvelope(probe);return {...probe,capabilityEnvelope:envelope};}
async function run(url){const initial=await nativeProbe(url,{url,allowNetwork:true});if(!initial?.ok)return initial;const initialEnvelope=await capabilityEnvelope(initial);if(!initialEnvelope?.ok)return {...initial,capabilityEnvelope:initialEnvelope};const dispatch=sourceDispatch(initialEnvelope);if(!dispatch)return {...initial,capabilityEnvelope:initialEnvelope,sourceDispatchError:'missing-or-invalid-source-dispatch'};if(dispatch.requiresRuntime!==true)return {...initial,capabilityEnvelope:initialEnvelope};const snapshot=await collect(url);const completed=await nativeProbe(url,{url,runtimeSnapshot:snapshot});if(!completed?.ok)return {...completed,capabilityEnvelope:initialEnvelope};return attachEnvelope(completed);}
browser.runtime.onMessage.addListener(message=>{if(!message||message.type!=='dore.runtime-source-probe')return undefined;const url=String(message.url||'').trim();if(!url)return Promise.resolve({ok:false,error:'url required'});return run(url).then(result=>({ok:Boolean(result&&result.ok),result})).catch(error=>({ok:false,error:String(error&&error.message||error)}));});
