#!/usr/bin/env python3
import json,tempfile
from pathlib import Path
from dawn_library_enrichment import enrich
from dawn_incremental_enrichment import incremental_enrich
from multi_loop_control_plane import register,wake,route,share,complete,consume,load
first=enrich();existing=first['sources'][:32];consumed={str(x.get('id') or x.get('url')) for x in existing};delta=incremental_enrich(consumed,[first['knowledge_id']])
with tempfile.TemporaryDirectory() as d:
 state=Path(d)/'state.json';assets=Path(d)/'assets.jsonl';register('storybook-reference-expansion','32 to 40',kind='storybook',priority=60,state_path=state,metadata={'references':existing,'current_qualified_references':32,'minimum_qualified_references':40});wake('storybook-reference-expansion','continue',state_path=state);route(state_path=state);register('dawn-library-enrichment','incremental enrichment',kind='dawn-library',priority=65,state_path=state,metadata={'baseline_asset':first['knowledge_id']});wake('dawn-library-enrichment','missing-source-families',gravity=25,state_path=state);route(state_path=state);receipt=share('dawn-library-enrichment',delta,state_path=state,asset_path=assets);complete('dawn-library-enrichment',state_path=state);reuse=consume('storybook-reference-expansion',delta,state_path=state);all_ids=consumed|{x['id'] for x in delta['sources']};repeat=incremental_enrich(all_ids,[first['knowledge_id'],delta['knowledge_id']]);data=load(state);row=data['workflows']['storybook-reference-expansion'];passed=reuse['total']>=40 and reuse['source_families']>=6
 if_pass='PASS' if passed else 'ACTIVE';row['status']=if_pass
 checks={'baseline_is_32':len(existing)==32,'consumed_32_not_returned':not consumed.intersection({x['id'] for x in delta['sources']}),'delta_at_least_8':delta['source_count']>=8,'provenance_and_rights_complete':delta['provenance_preserved'] and delta['rights_preserved'],'source_family_threshold':delta['source_family_count']>=6 and reuse['source_families']>=6,'working_set_reaches_40':reuse['total']>=40,'repeat_after_consumption_returns_zero':repeat['source_count']==0,'second_research_scope_lower_than_first':delta['candidate_examined_count']<first['source_count'],'storybook_goal_pass':passed and row['status']=='PASS','asset_shared_once':receipt['ok'] and not receipt['deduplicated']}
 out={'ok':all(checks.values()),'code':'DORE_DAWN_INCREMENTAL_ENRICHMENT_1_PASS' if all(checks.values()) else 'DORE_DAWN_INCREMENTAL_ENRICHMENT_1_FAIL','checks':checks,'reference_delta':{'before':32,'new':reuse['new_references'],'after':reuse['total'],'target':40},'source_families':delta['source_families'],'cost_evidence':{'first_scope':first['source_count'],'incremental_scope':delta['candidate_examined_count'],'repeat_returned':repeat['source_count']},'knowledge_asset':delta['knowledge_id']};print(json.dumps(out,ensure_ascii=False));raise SystemExit(0 if out['ok'] else 1)
