#!/usr/bin/env python3
from __future__ import annotations
import importlib,json,os,tempfile

def main():
 with tempfile.TemporaryDirectory() as td:
  os.environ["DORE_TWO_DAYS_HOME"]=td
  import two_days_artifact_ledger as ledger;ledger=importlib.reload(ledger)
  import two_days_today as today;today=importlib.reload(today)
  aid="the-gate/03"
  v1="第三篇｜V1\n这是已经确认的正文。"
  v3="第三篇｜新标题\n这是已经确认的正文。"
  ledger.put_version(aid,"V1",v1);ledger.apply("e1",aid,"TEXT_PROPOSED",to_version="V1");ledger.apply("e2",aid,"TEXT_ACCEPTED",to_version="V1")
  ledger.put_version(aid,"V3",v3);ledger.apply("e3",aid,"TEXT_REPLACED",from_version="V1",to_version="V3",metadata={"reason":"保留新标题"})
  resume={"artifact_id":aid,"instruction":"继续第三篇，V3 尚未确认","unfinished_edge":"标题已换，正文沿用 V1"}
  first=today.commit(aid,resume);assert today.verify(first["today"])["ok"]
  assert first["today"]["work_heads"][aid]["accepted_head"]["version_id"]=="V1"
  assert first["today"]["work_heads"][aid]["working_head"]["version_id"]=="V3"
  # TODAY is disposable. Delete it and reconstruct from durable ledger.
  os.remove(first["path"]);assert not os.path.exists(first["path"])
  second=today.commit(aid,resume);assert today.verify(second["today"])["ok"]
  assert first["projection_sha256"]==second["projection_sha256"]
  # Process restart must preserve the same logical TODAY.
  today=importlib.reload(today);third=today.read();assert today.verify(third)["ok"]
  assert today.canonical(first["today"])==today.canonical(third)
  # Exact manuscript comes from version authority, never regenerated by TODAY.
  assert ledger.content(aid,"V1")==v1 and ledger.content(aid,"V3")==v3
  print(json.dumps({"ok":True,"code":"TWO_DAYS_TODAY_PHASE3_PASS","rebuild":"PASS","restart":"PASS","accepted_head":"V1","working_head":"V3","projection_sha256":second["projection_sha256"]},ensure_ascii=False))
if __name__=="__main__":main()
