document.documentElement.dataset.surface='paradise-cinema';
document.documentElement.dataset.core='dore';
const library=document.querySelector('#cinema-library'),feature=document.querySelector('#cinema-feature'),dialog=document.querySelector('#cinema-player'),stage=document.querySelector('#player-stage'),closeButton=document.querySelector('.player-close');
let resources=[],resourceById=new Map();const JESUS_ID='cinema:video:jesus-film:jesus';
const excluded=new Set(['sermon','teaching','course','bible-study','visual-commentary','scripture-overview']);
function sourceFor(item){return (item.sources||item.providerSources||[])[0]||{};}
function playbackTarget(item,startMs=0){return window.HolyLightProviders?.resolve(item,Math.max(0,Math.floor(startMs/1000)))||null;}
function openAt(item,startMs=0){const target=playbackTarget(item,startMs);if(!target)return;if(target.kind==='embed'){stage.replaceChildren();window.HolyLightProviders.mount(stage,item,Math.floor(startMs/1000));dialog.showModal();}else window.open(target.url,'_blank','noopener,noreferrer');}
function renderScreen(item){if(!feature||!item)return;const target=playbackTarget(item,0),playable=target?.kind==='embed',shell=document.createElement('article');shell.className='cinema-feature';shell.dataset.canonicalId=item.canonicalId;const visual=document.createElement('div');visual.className='cinema-feature__visual';const media=document.createElement('div');media.className='cinema-feature__media';media.setAttribute('aria-label',`${item.title} player`);const curtain=document.createElement('button');curtain.type='button';curtain.className='cinema-feature__curtain';curtain.innerHTML=`<span>${playable?'PLAY':'PROGRAMME'}</span>`;visual.append(media,curtain);const copy=document.createElement('div');copy.className='cinema-feature__copy';copy.innerHTML=`<p>${playable?'NOW SHOWING · PLAYABLE HERE':'PROGRAMME · OFFICIAL VIEWING'}</p><h2></h2><p class="cinema-feature__creator"></p>`;copy.querySelector('h2').textContent=item.title;copy.querySelector('.cinema-feature__creator').textContent=item.creator||item.series||'';shell.append(visual,copy);curtain.addEventListener('click',()=>{if(playable&&window.HolyLightProviders?.mount(media,item,0)){curtain.hidden=true;shell.dataset.state='playing';return;}openAt(item,0);});feature.replaceChildren(shell);document.documentElement.dataset.cinemaScreenWork=item.canonicalId;document.documentElement.dataset.cinemaScreenPlayable=playable?'true':'false';}
function renderCard(item){const playable=playbackTarget(item,0)?.kind==='embed',card=document.createElement('article');card.className='resource-card';card.dataset.canonicalId=item.canonicalId;const meta=document.createElement('div');meta.className='resource-meta';meta.textContent=`${playable?'PLAYABLE':'PROGRAMME'} · ${item.kind||'film'} · ${item.creator||''}`;const title=document.createElement('h3');title.textContent=item.title;const series=document.createElement('p');series.textContent=item.series||'';const action=document.createElement('button');action.className='resource-action';action.type='button';action.textContent=playable?'在銀幕播放':'節目介紹／官方觀看';action.addEventListener('click',()=>{if(playable){renderScreen(item);document.querySelector('#cinema-screen')?.scrollIntoView({behavior:'smooth',block:'start'});}else openAt(item,0);});card.append(meta,title,series,action);return card;}
function selectProgrammeWork(workId){const item=resourceById.get(workId);if(!item)return false;renderScreen(item);document.querySelectorAll('[data-programme-selected]').forEach(node=>delete node.dataset.programmeSelected);document.querySelector(`[data-canonical-id="${CSS.escape(workId)}"]`)?.setAttribute('data-programme-selected','true');return true;}
async function loadCinema(){try{const [graph,curatedResponse]=await Promise.all([window.ParadiseCinemaGraph?.ready,fetch('data/video-resource-curated.v1.json',{cache:'no-store'})]);if(!graph||!Array.isArray(graph.works)||!curatedResponse.ok)throw new Error('Cinema resources unavailable');const curated=await curatedResponse.json();if(curated.schema!=='dore.cinema-resource-expansion.v1')throw new Error('Invalid curated resource schema');const merged=[...graph.works,...curated.items];const unique=new Map();for(const item of merged)if(!excluded.has(item.kind))unique.set(item.canonicalId,item);resources=[...unique.values()];resourceById=new Map(resources.map(item=>[item.canonicalId,item]));library.replaceChildren(...resources.map(renderCard));const scheduled=window.ParadiseCinemaProgramme?.selected?.workId;selectProgrammeWork(scheduled)||renderScreen(resourceById.get(JESUS_ID)||resources[0]);document.documentElement.dataset.cinemaResources=String(resources.length);document.documentElement.dataset.cinemaCurated='v1';}catch(error){library.innerHTML='<p class="resource-card">館藏資料暫時無法載入。</p>';if(feature)feature.innerHTML='<p class="resource-card">銀幕暫時無法載入。</p>';document.documentElement.dataset.cinemaError='resource-load';}}
window.addEventListener('paradise-cinema:programme',event=>selectProgrammeWork(event.detail?.workId));closeButton?.addEventListener('click',()=>dialog.close());dialog?.addEventListener('close',()=>stage.replaceChildren());dialog?.addEventListener('click',event=>{if(event.target===dialog)dialog.close();});loadCinema();
