document.documentElement.dataset.surface='paradise-cinema';
document.documentElement.dataset.core='dore';
const library=document.querySelector('#cinema-library'),feature=document.querySelector('#cinema-feature');
let resources=[],programmeResources=[],resourceById=new Map();const JESUS_ID='cinema:video:jesus-film:jesus';
const excluded=new Set(['sermon','teaching','course','bible-study','visual-commentary','scripture-overview']);
function sourceFor(item){return (item.providerSources||[])[0]||{};}
function youtubeId(source){const raw=source.embedUrl||source.url||'';const m=raw.match(/(?:embed\/|v=|youtu\.be\/)([A-Za-z0-9_-]{11})/);return m?.[1]||null;}
function posterCandidates(item){const source=sourceFor(item),explicit=source.preview?.posterUrl,id=youtubeId(source),list=[];if(explicit)list.push(explicit);if(id)list.push(`https://i.ytimg.com/vi/${id}/hqdefault.jpg`,`https://i.ytimg.com/vi/${id}/mqdefault.jpg`);return [...new Set(list)];}
function playbackTarget(item){return window.HolyLightProviders?.resolve(item,0)||null;}
function programmeReady(item){return playbackTarget(item)?.kind==='embed'&&posterCandidates(item).length>0;}
function renderScreen(item){if(!feature||!item||!programmeReady(item))return;const posters=posterCandidates(item),shell=document.createElement('article');shell.className='cinema-feature';shell.dataset.canonicalId=item.canonicalId;const visual=document.createElement('div');visual.className='cinema-feature__visual';const media=document.createElement('div');media.className='cinema-feature__media';const img=document.createElement('img');img.className='cinema-feature__poster';img.alt=`${item.title} preview`;let i=0;const next=()=>{if(i<posters.length)img.src=posters[i++];};img.onerror=next;next();media.appendChild(img);const play=document.createElement('button');play.type='button';play.className='cinema-feature__curtain cinema-feature__play';play.innerHTML='<span>PLAY</span>';play.onclick=()=>{const mounted=window.HolyLightProviders?.mount(media,item,0);if(mounted){shell.dataset.state='playing';play.remove();}};visual.append(media,play);const copy=document.createElement('div');copy.className='cinema-feature__copy';copy.innerHTML='<p>NOW SHOWING</p><h2></h2><p class="cinema-feature__creator"></p>';copy.querySelector('h2').textContent=item.title;copy.querySelector('.cinema-feature__creator').textContent=item.creator||item.series||'';shell.append(visual,copy);feature.replaceChildren(shell);document.documentElement.dataset.cinemaScreenWork=item.canonicalId;}
function renderCard(item){const ready=programmeReady(item),source=sourceFor(item),card=document.createElement('article');card.className='resource-card';card.dataset.canonicalId=item.canonicalId;card.innerHTML=`<div class="resource-meta">${ready?'PLAYABLE HERE':'COLLECTION'} · ${item.kind||'film'}</div><h3></h3><p></p>`;card.querySelector('h3').textContent=item.title;card.querySelector('p').textContent=item.series||item.creator||'';const button=document.createElement('button');button.className='resource-action';button.type='button';button.textContent=ready?'在銀幕播放':'查看來源 ↗';button.onclick=()=>{if(ready){renderScreen(item);document.querySelector('#cinema-screen')?.scrollIntoView({behavior:'smooth',block:'center'});}else if(source.url||source.embedUrl)window.open(source.url||source.embedUrl,'_blank','noopener,noreferrer');};card.append(button);return card;}
function selectProgrammeWork(id){const item=resourceById.get(id);if(!item||!programmeReady(item))return false;renderScreen(item);return true;}
async function loadCinema(){try{const [graph,response]=await Promise.all([window.ParadiseCinemaGraph?.ready,fetch('data/video-resource-curated.v1.json',{cache:'no-store'})]);const curated=await response.json(),unique=new Map();for(const item of [...graph.works,...curated.items])if(!excluded.has(item.kind))unique.set(item.canonicalId,item);resources=[...unique.values()];programmeResources=resources.filter(programmeReady);resourceById=new Map(resources.map(x=>[x.canonicalId,x]));library.replaceChildren(...resources.map(renderCard));const scheduled=window.ParadiseCinemaProgramme?.selected?.workId;selectProgrammeWork(scheduled)||renderScreen(programmeResources.find(x=>x.canonicalId===JESUS_ID)||programmeResources[0]);document.documentElement.dataset.cinemaAdmission='preview-plus-direct-embed';}catch(e){library.innerHTML='<p class="resource-card">館藏資料暫時無法載入。</p>';feature.innerHTML='<p class="resource-card">銀幕暫時無法載入。</p>';}}
window.addEventListener('paradise-cinema:programme',e=>selectProgrammeWork(e.detail?.workId));loadCinema();
