#!/usr/bin/env python3
"""Visible Design 2.0 product shell. Lightweight, dependency-free, same workspace/canvas APIs."""

def install(html):
    css=r'''<style id="dore-design2-ui">
:root{--d2-bg:#171816;--d2-panel:#f4f1e9;--d2-paper:#fbfaf6;--d2-ink:#24231f;--d2-muted:#777269;--d2-line:#d9d3c7;--d2-gold:#b49a55;--d2-rail:54px}
html,body{background:var(--d2-bg)!important;font-family:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif!important}.top{height:52px!important;background:#11120f!important;border:0!important;padding:0 16px!important;gap:5px!important}.top strong{font-family:Georgia,"Times New Roman",serif;font-size:16px;font-weight:400;letter-spacing:.03em}.top strong:after{content:"  2.0";color:var(--d2-gold);font:10px Inter,sans-serif;letter-spacing:.14em}.top button,.top a{border:0!important;background:transparent!important;color:#aaa!important;border-radius:5px;padding:7px 9px!important}.top button:hover,.top a:hover{background:#24251f!important;color:white!important}.status{font:10px ui-monospace,monospace;color:#c6b06d!important}.work{height:calc(100% - 52px)!important;grid-template-columns:258px minmax(0,1fr) 286px!important}.side{background:var(--d2-panel)!important;border-color:var(--d2-line)!important;padding:16px 14px!important}.side h3{font:600 9px Inter,sans-serif!important;letter-spacing:.16em;color:#8b8579;margin:16px 4px 8px!important}.side h3:first-child{margin-top:0!important}.page{border:0!important;background:transparent!important;border-radius:7px;margin:2px 0!important;padding:9px 10px!important;font-family:Inter,sans-serif!important}.page:hover{background:#ebe6dc!important}.page.active{border:0!important;background:#ded6c5!important;box-shadow:inset 2px 0 var(--d2-gold)}.page b{font-size:12px;font-weight:600}.page small{margin-top:3px;display:block;font-size:9px;color:#8a8479}.layer{border:0!important;border-radius:5px;padding:7px 9px!important;font-size:10px;color:#59554d}.layer:hover,.layer.active{background:#e6dfd1!important}.canvaswrap{position:relative;background:#292a27!important;padding:32px!important}.canvaswrap:before{content:"CANVAS";position:absolute;top:10px;left:16px;color:#777;font:8px Inter,sans-serif;letter-spacing:.18em}.canvas{border-radius:2px;box-shadow:0 18px 60px #0007!important}.right label{font:600 8px Inter,sans-serif!important;letter-spacing:.13em;color:#999187!important}.right textarea{border:1px solid var(--d2-line)!important;border-radius:6px;background:var(--d2-paper);font:13px/1.5 Inter,sans-serif!important}.right button{border-radius:6px!important;background:#272721!important}.hint{font:11px/1.55 Inter,sans-serif!important;color:#817b71!important}.candidate-card{background:transparent!important;color:var(--d2-ink)!important;border:1px solid var(--d2-line)!important;border-radius:6px!important}.candidate-card.on{outline:1px solid var(--d2-gold)!important}.candidate-card small{color:#9b854c!important}.judge-actions button:last-child{background:#72504b!important}
#d2-rail{position:fixed;z-index:20;left:50%;bottom:17px;transform:translateX(-50%);display:flex;gap:3px;padding:5px;background:#11120fe8;border:1px solid #393a35;border-radius:9px;box-shadow:0 8px 24px #0005}#d2-rail button{width:34px;height:30px;border:0;border-radius:5px;background:transparent;color:#aaa;font:13px Inter,sans-serif;cursor:pointer}#d2-rail button:hover{background:#30312c;color:#fff}#d2-rail .on{color:#d1b86f;background:#2b2b25}
#d2-dore{position:fixed;z-index:21;right:302px;top:62px;padding:6px 9px;border:1px solid #494a44;border-radius:999px;background:#171814d9;color:#cbb675;font:9px Inter,sans-serif;letter-spacing:.08em;pointer-events:none}
</style>'''
    rail=r'''<div id="d2-dore">DORÉ · SAME ARTIFACT</div><div id="d2-rail" aria-label="Canvas tools"><button class="on" title="Select">↖</button><button title="Frame">□</button><button title="Text">T</button><button title="Asset">◇</button><button title="Command">⌘</button></div>'''
    return html.replace('</head>',css+'</head>').replace('</body>',rail+'</body>').replace('DORÉ DESIGN 1.9 · PROMOTION PIPELINE','DORÉ DESIGN')
