#!/usr/bin/env python3
"""Canvas state bridge: visibility, locking, grouping and alignment for Design 2.0."""
CSS='''<style id="d2-canvas-state-css">
[data-d2-hidden="1"]{display:none!important}[data-d2-locked="1"]{cursor:not-allowed!important;outline-style:dotted!important}.d2-group-peer{outline:1px solid rgba(180,154,85,.34)!important;outline-offset:2px}
</style>'''
JS=r'''<script id="d2-canvas-state-js">(()=>{const page='multiwrite-home',canvas=document.querySelector('.canvas');if(!canvas)return;let primary=null,selectedIds=[];const nodes=()=>[...canvas.querySelectorAll('[data-id]')];async function workspace(){return fetch('/api/workspace',{cache:'no-store'}).then(r=>r.json())}async function sync(){const w=await workspace(),p=(w.pages||[]).find(x=>x.id===page);if(!p)return;for(const n of p.nodes||[]){const el=canvas.querySelector('[data-id="'+CSS.escape(n.id)+'"]');if(!el)continue;el.dataset.d2Hidden=n.hidden?'1':'0';el.dataset.d2Locked=n.locked?'1':'0';if(n.group_id)el.dataset.groupId=n.group_id;else delete el.dataset.groupId}}function markGroup(el){nodes().forEach(n=>n.classList.remove('d2-group-peer'));if(!el?.dataset.groupId)return;nodes().filter(n=>n.dataset.groupId===el.dataset.groupId).forEach(n=>n.classList.add('d2-group-peer'))}canvas.addEventListener('pointerdown',e=>{const n=e.target.closest('[data-id]');if(!n)return;if(n.dataset.d2Locked==='1'){e.preventDefault();e.stopImmediatePropagation();parent.postMessage({type:'dore-locked',page_id:page,id:n.dataset.id},'*');return}primary=n;selectedIds=e.shiftKey?[...new Set([...selectedIds,n.dataset.id])]:[n.dataset.id];markGroup(n);parent.postMessage({type:'dore-selection-set',page_id:page,ids:selectedIds,primary:n.dataset.id},'*')},true);window.addEventListener('message',async e=>{const m=e.data||{};if(m.type!=='d2-canvas-command'||m.page_id!==page)return;const ids=(m.ids||selectedIds).filter(Boolean);if(!ids.length)return;const r=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({op:m.op,page_id:page,ids,mode:m.mode,group_id:m.group_id})});if(!r.ok)return parent.postMessage({type:'dore-error',page_id:page},'*');await sync();parent.postMessage({type:'dore-saved',page_id:page},'*');if(m.op==='align_nodes')location.reload()});sync()})()</script>'''
def augment(html):
    if 'class="canvas"' not in html:return html
    return html.replace('</head>',CSS+'</head>',1).replace('</body>',JS+'</body>',1)
