"""DORÉ DESIGN 2.0 contextual element inspector injection."""
CSS='''<style id="dore2-style">.d2{border:1px solid #c8c4b8;background:#fff;margin:0 0 14px;padding:10px}.d2[hidden]{display:none}.d2-grid{display:grid;grid-template-columns:1fr 1fr;gap:6px}.d2 label{display:block;margin:7px 0 2px;font:10px ui-monospace,monospace;color:#666}.d2 input,.d2 select{width:100%;padding:6px;border:1px solid #aaa;background:#fff}.d2-align{display:grid;grid-template-columns:repeat(3,1fr);gap:3px;margin-top:7px}.d2 button{padding:6px;border:1px solid #aaa;background:#f7f6f2;cursor:pointer}.d2 .meta{font:10px/1.4 ui-monospace,monospace;color:#777;margin:4px 0 8px}</style>'''
PANEL='''<section id="dore2Inspector" class="d2" hidden><h3>ELEMENT · 2.0</h3><div id="d2meta" class="meta"></div><div class="d2-grid"><div><label>X</label><input id="d2x" type="number" step="1"></div><div><label>Y</label><input id="d2y" type="number" step="1"></div><div><label>W</label><input id="d2w" type="number" min="1" step="1"></div><div><label>SIZE</label><input id="d2size" type="number" min="6" max="300" step="1"></div></div><label>TEXT ALIGN</label><div class="d2-align"><button data-a="left">Left</button><button data-a="center">Center</button><button data-a="right">Right</button></div></section>'''
JS=r'''<script id="dore2-js">(()=>{let sel=null;const $=id=>document.getElementById(id),box=$('dore2Inspector');function pg(){return ws?.pages?.find(p=>p.id===active)}function node(){return pg()?.nodes?.find(n=>n.id===sel)}function sync(){const n=node();box.hidden=!n;if(!n)return;$('d2meta').textContent=n.id+' · '+n.type+' · document coordinates';for(const [id,k] of [['d2x','x'],['d2y','y'],['d2w','w'],['d2size','size']])$(id).value=n[k]??'';box.querySelectorAll('[data-a]').forEach(b=>b.style.fontWeight=(n.text_align||'left')===b.dataset.a?'700':'400')}async function patch(p){const n=node();if(!n)return;const rev=ws.revision,r=await fetch('/api/design2/command',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expected_revision:rev,command:{op:'node.patch',page_id:active,id:n.id,patch:p}})});const data=await r.json();if(!r.ok){$('status').textContent=data.error||'2.0 command failed';return}ws=data.workspace;renderLayers();$('canvas').src=canvasUrl();sync();$('status').textContent='DORÉ 2.0 · r'+ws.revision}for(const [id,k] of [['d2x','x'],['d2y','y'],['d2w','w'],['d2size','size']])$(id).addEventListener('change',e=>{if(e.target.value!=='')patch({[k]:Number(e.target.value)})});box.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>patch({text_align:b.dataset.a}));window.addEventListener('message',e=>{if(e.data?.type==='dore-select'&&e.data.page_id===active){sel=e.data.id;sync()}});document.addEventListener('keydown',e=>{if(!sel||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();const d=e.shiftKey?10:1,dx=e.key==='ArrowLeft'?-d:e.key==='ArrowRight'?d:0,dy=e.key==='ArrowUp'?-d:e.key==='ArrowDown'?d:0;const n=node();fetch('/api/design2/command',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expected_revision:ws.revision,command:{op:'node.nudge',page_id:active,ids:[n.id],dx,dy}})}).then(r=>r.json()).then(data=>{if(data.workspace){ws=data.workspace;renderLayers();$('canvas').src=canvasUrl();sync();$('status').textContent='DORÉ 2.0 · r'+ws.revision}})});setTimeout(sync,0)})()</script>'''


def augment(html):
    if 'id="inspector"' not in html: raise RuntimeError('design2_inspector_marker_missing')
    html=html.replace('</head>',CSS+'</head>',1)
    html=html.replace('<h3>INSPECTOR</h3>',PANEL+'<h3>INSPECTOR</h3>',1)
    return html.replace('</body>',JS+'</body>',1)
