#!/usr/bin/env python3
"""Locked #262 homepage renderer plus Doré editing chrome.

The approved homepage template is never rewritten here. Preview and editor canvas
render the exact same template; /editor only wraps that canvas with tooling.
"""
from pathlib import Path
ROOT=Path(__file__).resolve().parent.parent
TEMPLATE=ROOT/'dore-design/new-westside/homepage-v2-living-fortress.html'

BINDINGS=[
('<div class="hero-kicker micro">Westside Watch / 西望</div>','<div class="hero-kicker micro dore-bound" data-node-id="watch-kicker" data-field="text">Westside Watch / 西望</div>'),
('<h1>WATCH<br>FOR THE <em>DAWN.</em></h1>','<h1 class="dore-bound" data-node-id="home-title" data-field="text">WATCH<br>FOR THE <em>DAWN.</em></h1>'),
('<p>在黑夜仍然守望，在清晨尚未來到以前保存光。文章、聖經、教會生活與研究，在同一座城中彼此照亮。</p>','<p class="dore-bound" data-node-id="home-deck" data-field="text">在黑夜仍然守望，在清晨尚未來到以前保存光。文章、聖經、教會生活與研究，在同一座城中彼此照亮。</p>'),
('<div class="verse micro">The night is far spent,<br>the day is at hand.<br>Romans 13:12</div>','<div class="verse micro dore-bound" data-node-id="verse" data-field="text">The night is far spent,<br>the day is at hand.<br>Romans 13:12</div>'),
('<strong>一個入口，四條路。</strong>','<strong class="dore-bound" data-node-id="threshold-title" data-field="text">一個入口，四條路。</strong>'),
('<span class="micro">Read · Study · Gather · Remember</span>','<span class="micro dore-bound" data-node-id="threshold-meta" data-field="text">Read · Study · Gather · Remember</span>'),
('<span class="eyebrow micro">Journal · Current volume</span>','<span class="eyebrow micro dore-bound" data-node-id="journal-tower" data-field="eyebrow">Journal · Current volume</span>'),
('<h2>守望，<br>一座光明的城</h2>','<h2 class="dore-bound" data-node-id="journal-tower" data-field="title">守望，<br>一座光明的城</h2>'),
('<p>進入本期 Journal。圖像、文字、見證與禱告在一個獨立的閱讀世界中展開。</p>','<p class="dore-bound" data-node-id="journal-tower" data-field="body">進入本期 Journal。圖像、文字、見證與禱告在一個獨立的閱讀世界中展開。</p>'),
('<span class="eyebrow micro">ONE · Bible study</span>','<span class="eyebrow micro dore-bound" data-node-id="one-territory" data-field="eyebrow">ONE · Bible study</span>'),
('<h2>路上，祂向我們打開聖經。</h2>','<h2 class="dore-bound" data-node-id="one-territory" data-field="title">路上，祂向我們打開聖經。</h2>'),
('<p>從一章、一卷書、一條路線開始，把經文、歷史、地圖與串珠重新連起來。</p>','<p class="dore-bound" data-node-id="one-territory" data-field="body">從一章、一卷書、一條路線開始，把經文、歷史、地圖與串珠重新連起來。</p>'),
('<span class="eyebrow micro">Living Water West</span>','<span class="eyebrow micro dore-bound" data-node-id="church-territory" data-field="eyebrow">Living Water West</span>'),
('<h2>一座城，<br>也是一個家。</h2>','<h2 class="dore-bound" data-node-id="church-territory" data-field="title">一座城，<br>也是一個家。</h2>'),
('<p>Sunday Worship · Bible Study · Prayer · Life Together</p>','<p class="dore-bound" data-node-id="church-territory" data-field="body">Sunday Worship · Bible Study · Prayer · Life Together</p>'),
('<span class="eyebrow micro">Dawn Library · 黎明書局</span>','<span class="eyebrow micro dore-bound" data-node-id="library-territory" data-field="eyebrow">Dawn Library · 黎明書局</span>'),
('<h2>被保存的光。</h2>','<h2 class="dore-bound" data-node-id="library-territory" data-field="title">被保存的光。</h2>'),
('<p>地圖、文章、史料與研究資源逐步沉澱，成為可以再次被調用的知識。</p>','<p class="dore-bound" data-node-id="library-territory" data-field="body">地圖、文章、史料與研究資源逐步沉澱，成為可以再次被調用的知識。</p>'),
('<span class="eyebrow micro">The Gate</span>','<span class="eyebrow micro dore-bound" data-node-id="join-territory" data-field="eyebrow">The Gate</span>'),
('<h2>Come<br>and see.</h2>','<h2 class="dore-bound" data-node-id="join-territory" data-field="title">Come<br>and see.</h2>'),
('<h3>從閱讀走向相遇。</h3>','<h3 class="dore-bound" data-node-id="gate-copy-left" data-field="text">從閱讀走向相遇。</h3>'),
('<h3>從守望走向黎明。</h3>','<h3 class="dore-bound" data-node-id="gate-copy-right" data-field="text">從守望走向黎明。</h3>'),
('<div class="number">12</div>','<div class="number dore-bound" data-node-id="watch-number" data-field="text">12</div>'),
('黑夜已深，<br>白晝將近。','<span class="dore-bound" data-node-id="watch-quote" data-field="text">黑夜已深，<br>白晝將近。</span>'),
('<cite class="micro">Romans 13:12 · Watch for the Dawn</cite>','<cite class="micro dore-bound" data-node-id="watch-cite" data-field="text">Romans 13:12 · Watch for the Dawn</cite>')]

CANVAS_CSS='''.dore-bound{white-space:pre-line}body[data-dore-canvas="true"] .dore-bound{cursor:text;outline:1px dashed transparent;outline-offset:4px}body[data-dore-canvas="true"] .dore-bound:hover{outline-color:rgba(179,154,71,.7)}body[data-dore-canvas="true"] .dore-bound:focus{outline:2px solid #d0bd78;background:rgba(208,189,120,.08)}'''
CANVAS_JS=r'''<script>(()=>{const edit=document.body.dataset.doreCanvas==='true';const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let w=null,h=null;function n(id){return h?.nodes?.find(x=>x.id===id)}function paint(el,v,id){v=String(v??'');if(id==='home-title'){const a=v.split(/\n+/).filter(Boolean);el.innerHTML=a.map((x,i)=>i===a.length-1?'<em>'+esc(x)+'</em>':esc(x)).join('<br>')}else el.textContent=v}async function load(){w=await(await fetch('/api/workspace',{cache:'no-store'})).json();h=w.pages.find(p=>p.id==='homepage')||w.pages[0];document.querySelectorAll('[data-node-id]').forEach(el=>{const x=n(el.dataset.nodeId),f=el.dataset.field||'text';if(x&&x[f]!==undefined)paint(el,x[f],x.id);if(edit){el.contentEditable='true';el.spellcheck=false;el.addEventListener('focus',()=>parent.postMessage({type:'dore-select',id:el.dataset.nodeId,field:f,value:el.innerText},'*'))}});parent.postMessage({type:'dore-ready',revision:w.revision},'*')}async function save(el){const id=el.dataset.nodeId,f=el.dataset.field||'text',v=el.innerText.replace(/\n{3,}/g,'\n\n').trim();const r=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({op:'set_node',page_id:'homepage',id,patch:{[f]:v}})});if(!r.ok){parent.postMessage({type:'dore-error'},'*');return}w=await r.json();h=w.pages.find(p=>p.id==='homepage')||w.pages[0];paint(el,v,id);parent.postMessage({type:'dore-saved',revision:w.revision,id,field:f,value:v},'*')}if(edit){document.addEventListener('blur',e=>{const el=e.target.closest?.('[data-node-id]');if(el)save(el)},true);document.addEventListener('click',e=>{if(e.target.closest('.portal,.gate-mark'))e.preventDefault()},true)}load().catch(()=>parent.postMessage({type:'dore-error'},'*'))})();</script>'''

def render_canvas(edit=False):
    html=TEMPLATE.read_text(encoding='utf-8').replace('/images/westside-watch-masthead-landscape.svg','/asset/masthead.svg').replace('/images/westside-watch-morning-star.svg','/asset/morning-star.svg')
    for old,new in BINDINGS: html=html.replace(old,new)
    html=html.replace('</style>',CANVAS_CSS+'</style>',1)
    if edit: html=html.replace('<body>','<body data-dore-canvas="true">',1)
    return html.replace('</body>',CANVAS_JS+'</body>',1)

EDITOR_HTML=r'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Doré Design — Editor</title><style>
*{box-sizing:border-box}html,body{margin:0;height:100%;overflow:hidden;background:#b9b9b6;color:#171717;font:11px ui-monospace,SFMono-Regular,Menlo,monospace}.top{height:44px;background:#171717;color:#eee;display:flex;align-items:center;gap:7px;padding:0 10px;border-bottom:1px solid #000}.top strong{letter-spacing:.07em}.top a,.top button{color:#eee;background:#303030;border:1px solid #555;padding:6px 9px;text-decoration:none;font:inherit;cursor:pointer}.status{margin-left:auto;color:#d0bd78}.work{height:calc(100% - 44px);display:grid;grid-template-columns:220px minmax(0,1fr) 250px}.side{background:#f3f3ef;overflow:auto;padding:12px;border-right:1px solid #aaa}.right{border-right:0;border-left:1px solid #aaa}.side h3{font-size:10px;letter-spacing:.14em;margin:0 0 10px}.page{padding:10px;border:1px solid #777;background:#fff;margin-bottom:12px;font-family:Arial,sans-serif;font-weight:700}.layer{padding:6px 3px;border-bottom:1px solid #ddd;cursor:pointer}.layer:hover,.layer.active{background:#e8dfc8}.canvaswrap{overflow:auto;padding:18px;background:#b9b9b6}.canvas{width:100%;height:100%;border:0;background:white;box-shadow:0 0 0 1px #999}.right label{display:block;margin:12px 0 5px;color:#666}.right textarea{width:100%;min-height:150px;resize:vertical;border:1px solid #aaa;padding:8px;font:13px/1.45 Arial,sans-serif}.right button{width:100%;margin-top:8px;padding:8px;background:#222;color:white;border:0;cursor:pointer}.hint{font:12px/1.5 Arial,sans-serif;color:#555}
</style></head><body><div class="top"><strong>DORÉ DESIGN 1.5.1 · EDITOR</strong><a href="/">Preview</a><a href="/structure-editor">Structure</a><a href="/journal/">Journal Mirror</a><button id="verify">Verify</button><button id="refresh">Refresh</button><span id="status" class="status">loading…</span></div><div class="work"><aside class="side"><h3>PAGES</h3><div class="page">Homepage / Watch for the Dawn</div><h3>LAYERS</h3><div id="layers"></div></aside><main class="canvaswrap"><iframe id="canvas" class="canvas" src="/editor-canvas"></iframe></main><aside class="side right"><h3>INSPECTOR</h3><div id="empty" class="hint">Select text in the canvas or choose a layer.</div><div id="inspector" hidden><label>NODE</label><div id="node"></div><label>FIELD</label><div id="field"></div><label>VALUE</label><textarea id="value"></textarea><button id="save">Save field</button></div><p class="hint">Layout is locked to the approved #262 design. Editing changes workspace content only.</p></aside></div><script>
let ws=null,selected=null;const $=id=>document.getElementById(id);async function load(){ws=await(await fetch('/api/workspace',{cache:'no-store'})).json();const h=ws.pages.find(p=>p.id==='homepage')||ws.pages[0];$('layers').innerHTML='';for(const n of h.nodes||[]){for(const f of ['text','eyebrow','title','body'])if(n[f]!==undefined){const d=document.createElement('div');d.className='layer';d.textContent=n.id+' · '+f;d.onclick=()=>select(n.id,f,n[f],d);$('layers').appendChild(d)}}$('status').textContent='workspace r'+ws.revision+' · design locked'}function select(id,field,value,el){selected={id,field};document.querySelectorAll('.layer').forEach(x=>x.classList.remove('active'));if(el)el.classList.add('active');$('empty').hidden=true;$('inspector').hidden=false;$('node').textContent=id;$('field').textContent=field;$('value').value=value??''}window.addEventListener('message',e=>{const m=e.data||{};if(m.type==='dore-select')select(m.id,m.field,m.value);if(m.type==='dore-ready'||m.type==='dore-saved'){if(m.revision)$('status').textContent=(m.type==='dore-saved'?'saved · ':'workspace r')+m.revision+' · design locked';if(m.type==='dore-saved')load()}if(m.type==='dore-error')$('status').textContent='ERROR'});$('save').onclick=async()=>{if(!selected)return;const r=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({op:'set_node',page_id:'homepage',id:selected.id,patch:{[selected.field]:$('value').value}})});if(!r.ok){$('status').textContent='SAVE FAILED';return}ws=await r.json();$('status').textContent='saved · r'+ws.revision+' · design locked';$('canvas').contentWindow.location.reload();load()};$('refresh').onclick=()=>{$('canvas').contentWindow.location.reload();load()};$('verify').onclick=async()=>{const v=await(await fetch('/api/verify',{cache:'no-store'})).json();$('status').textContent=v.ok?'VERIFY PASS · r'+v.revision:'VERIFY FAIL'};load();
</script></body></html>'''

def render_editor(): return EDITOR_HTML

def render(edit=False):
    return render_editor() if edit else render_canvas(edit=False)
