#!/usr/bin/env python3
"""Render materially distinct, editable homepage candidates from shared workspace content."""
import homepage_wysiwyg

PAGES={
 'homepage-concept-index':('A · Luminous Index',r'''body{background:#eee9dc!important;color:#171714!important}.site-head,.hero,.threshold,.territories,.watch-band,.gate{background:#eee9dc!important;color:#171714!important}.hero{min-height:82vh!important;border-bottom:1px solid #171714!important}.hero-inner{display:grid!important;grid-template-columns:1.25fr .75fr!important;align-items:end!important}.hero h1{font-size:clamp(86px,12vw,190px)!important;line-height:.72!important;color:#171714!important}.hero h1 em{color:#a23b27!important}.hero-copy{max-width:30rem!important}.territories{display:grid!important;grid-template-columns:repeat(12,1fr)!important;gap:1px!important;background:#171714!important}.territory{background:#eee9dc!important;color:#171714!important;border:0!important}.territory:nth-child(1){grid-column:span 7!important}.territory:nth-child(2){grid-column:span 5!important}.territory:nth-child(n+3){grid-column:span 4!important}.watch-band{border-top:1px solid #171714!important}.micro,.eyebrow{color:#a23b27!important}'''),
 'homepage-concept-dispatch':('B · Midnight Dispatch',r'''body{background:#061722!important;color:#f4efe4!important}.site-head,.hero,.threshold,.territories,.watch-band,.gate{background:#061722!important;color:#f4efe4!important}.hero{min-height:100vh!important}.hero-inner{display:grid!important;grid-template-columns:.42fr .58fr!important;gap:6vw!important}.hero h1{font-size:clamp(92px,12vw,205px)!important;line-height:.68!important;transform:translateX(-.04em)!important}.hero h1 em{color:#f06f46!important}.hero-copy{border-left:1px solid #f06f46!important;padding-left:2rem!important}.threshold{background:#f06f46!important;color:#061722!important}.territories{display:grid!important;grid-template-columns:1fr 1fr!important;gap:0!important}.territory{min-height:60vh!important;border:1px solid rgba(244,239,228,.22)!important;background:#071f2e!important}.territory:nth-child(3n){background:#f4efe4!important;color:#061722!important}.micro,.eyebrow{color:#f06f46!important}.watch-band{background:#f4efe4!important;color:#061722!important}'''),
 'homepage-concept-folio':('C · Independent Folio',r'''body{background:#e7b8a6!important;color:#241913!important}.site-head{background:#f4e3b2!important;color:#241913!important}.hero{min-height:92vh!important;background:#d9503f!important;color:#f9efcf!important}.hero-inner{display:grid!important;grid-template-columns:1fr 1fr!important}.hero h1{font-size:clamp(78px,10vw,165px)!important;line-height:.78!important;letter-spacing:-.055em!important}.hero h1 em{color:#f4e3b2!important;text-decoration:underline 4px!important}.hero-copy{transform:rotate(-2deg)!important;background:#f4e3b2!important;color:#241913!important;padding:2rem!important;box-shadow:12px 12px 0 #241913!important}.threshold{background:#241913!important;color:#f4e3b2!important}.territories{display:grid!important;grid-template-columns:repeat(3,1fr)!important;gap:1.2rem!important;padding:1.2rem!important;background:#e7b8a6!important}.territory{min-height:48vh!important;background:#f4e3b2!important;color:#241913!important;border:2px solid #241913!important;box-shadow:7px 7px 0 #241913!important}.territory:nth-child(even){transform:rotate(1deg)!important}.territory:nth-child(odd){transform:rotate(-.7deg)!important}.watch-band{background:#436c65!important;color:#f9efcf!important}.gate{background:#f4e3b2!important;color:#241913!important}.micro,.eyebrow{color:#d9503f!important}''')}

def render(page_id,edit=False):
 if page_id not in PAGES:raise ValueError('homepage_candidate_not_supported:'+str(page_id))
 name,css=PAGES[page_id];html=homepage_wysiwyg.render_canvas(edit=edit)
 html=html.replace("p.id==='homepage'",f"p.id==='{page_id}'").replace("page_id:'homepage'",f"page_id:'{page_id}'")
 html=html.replace('</style>',f'/* {name} */\n{css}</style>',1)
 return html.replace('<title>','<title>'+name+' · ',1)
