"""Living Water Candidate 03 — first layer only.
Candidate 01 color worlds are deliberately retained; motion/layout is rebuilt as weighted editorial composition.
"""
PAGE_ID='living-water-candidate-03'

def page():
    return {'id':PAGE_ID,'name':'Living Water · Candidate 03','canvas':{'w':1440,'h':960},'nodes':[],
      'design_experiment':{'schema':'dore.design-experiment.v1','track':'living-water-homepage','candidate':'03','status':'design-candidate','source':'user-sketch-2026-09-09',
      'principles':['candidate-01-color-worlds-frozen','first-layer-only','homepage-to-live-field','8:5-rhythm-unit','weighted-composition','composition-flows-not-cards','static-hierarchy-before-motion']}}

def install_workspace(base):
    original=base.workspace
    def workspace():
        w=original()
        if not any(p.get('id')==PAGE_ID for p in w.get('pages',[])):
            w['pages'].append(page());w=base.save(w)
        return w
    base.workspace=workspace

def install_editor(html):
    return html.replace("'living-water-candidate-02'])","'living-water-candidate-02','living-water-candidate-03'])")

def render(edit=False):
    badge='<div class="lab">DORÉ DESIGN · C03 · FIRST LAYER ONLY</div>' if edit else ''
    return '''<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Living Water · Candidate 03</title><style>
*{box-sizing:border-box}html{scroll-behavior:smooth}html,body{margin:0;background:#0c1720;color:#f7f1df;font-family:"Cormorant Garamond","Noto Serif TC",serif}body{overflow-x:hidden}.lab{position:fixed;z-index:99;top:12px;left:12px;padding:7px 10px;background:#f4eddc;color:#111;font:10px ui-monospace,monospace;letter-spacing:.12em}.micro{font:10px ui-monospace,monospace;letter-spacing:.18em;text-transform:uppercase}.goldtxt{color:#cebd74}.progress{position:fixed;z-index:80;left:0;top:0;height:3px;width:100%;background:#cebd74;transform-origin:left;animation:progress linear;animation-timeline:scroll(root block)}@keyframes progress{from{transform:scaleX(0)}to{transform:scaleX(1)}}
/* PAGE 1 — retain Candidate 01's opening color world */
.source{height:100svh;position:relative;overflow:hidden;isolation:isolate;background:#07121c}.engrave{position:absolute;inset:-8%;background:radial-gradient(ellipse at 65% 42%,rgba(206,189,116,.34),transparent 27%),repeating-radial-gradient(ellipse at 60% 48%,rgba(255,255,255,.045) 0 1px,transparent 1px 7px),linear-gradient(110deg,#07121c 0 28%,#183444 55%,#a2872a 120%);transform:scale(1.12)}.engrave:after{content:"";position:absolute;inset:0;background:repeating-linear-gradient(164deg,transparent 0 9px,rgba(250,249,245,.055) 9px 10px);mix-blend-mode:screen}.source-copy{position:absolute;z-index:3;left:7vw;bottom:10vh;max-width:760px}.source h1{font-size:clamp(62px,10vw,154px);font-weight:400;line-height:.77;margin:.16em 0}.source p{font-size:clamp(17px,1.7vw,25px);line-height:1.45;max-width:560px}.down{position:absolute;z-index:4;right:5vw;bottom:7vh;writing-mode:vertical-rl;color:#cebd74}
/* PAGE 2 — weighted editorial composition, not tracks/carousel */
.live{min-height:220svh;position:relative;background:#102a43;color:#faf9f5}.stage{height:100svh;position:sticky;top:0;overflow:hidden;padding:5.5vh 4.5vw 4vh}.field-head{height:23vh;display:grid;grid-template-columns:minmax(0,1.55fr) minmax(250px,.45fr);align-items:end;gap:5vw;padding-bottom:2.5vh;border-bottom:1px solid rgba(250,249,245,.22)}.field-head h2{font-size:clamp(50px,7.4vw,112px);font-weight:400;line-height:.78;margin:.12em 0}.field-head p{font-size:clamp(14px,1.2vw,19px);line-height:1.5;max-width:390px;margin:0 0 .4em}.composition{height:69vh;padding-top:2.5vh;display:grid;grid-template-columns:repeat(8,minmax(0,1fr));grid-template-rows:repeat(5,minmax(0,1fr));gap:1.05vw;position:relative}.unit{position:relative;overflow:hidden;min-width:0;border:1px solid rgba(255,255,255,.13);box-shadow:0 20px 60px rgba(0,0,0,.13);transition:grid-column .9s cubic-bezier(.2,.8,.2,1),grid-row .9s cubic-bezier(.2,.8,.2,1),transform .9s cubic-bezier(.2,.8,.2,1),opacity .7s}.unit:after{content:"";position:absolute;inset:0;background:linear-gradient(0deg,rgba(4,12,17,.68),transparent 67%);pointer-events:none}.unit .copy{position:absolute;z-index:2;left:1.4vw;right:1.4vw;bottom:1.2vw}.unit h3{font-size:clamp(23px,2.5vw,43px);font-weight:400;line-height:.9;margin:.15em 0}.unit p{font-size:13px;line-height:1.35;max-width:340px;margin:.45em 0 0}.journal{background:radial-gradient(circle at 65% 40%,rgba(210,188,105,.42),transparent 25%),linear-gradient(135deg,#07131d,#24485b);grid-column:1/5;grid-row:1/4}.cafe{background:linear-gradient(135deg,#f4efe2,#aaa18b);color:#252525;grid-column:5/7;grid-row:1/3}.cafe:after{background:linear-gradient(0deg,rgba(244,239,226,.9),transparent 65%)}.prayer{background:radial-gradient(circle at 30% 30%,rgba(250,249,245,.35),transparent 24%),linear-gradient(145deg,#425337,#8b9c72);grid-column:7/9;grid-row:1/3}.library{background:repeating-linear-gradient(90deg,rgba(0,0,0,.08) 0 1px,transparent 1px 17px),linear-gradient(135deg,#d2bc69,#8e6f25);color:#171713;grid-column:4/9;grid-row:3/6}.library:after{background:linear-gradient(0deg,rgba(245,239,220,.82),transparent 62%)}.one{background:linear-gradient(140deg,#486f83,#102936);grid-column:1/3;grid-row:4/6}.church{background:linear-gradient(140deg,#6f7d68,#263a2d);grid-column:3/4;grid-row:4/6}.weight{position:absolute;z-index:3;right:12px;top:11px;font:9px ui-monospace,monospace;letter-spacing:.14em;opacity:.78}.pulse{position:absolute;inset:-25%;border-radius:50%;background:radial-gradient(circle,rgba(206,189,116,.16),transparent 58%);animation:slowlight 12s ease-in-out infinite alternate;pointer-events:none}@keyframes slowlight{to{transform:translate3d(8%,-4%,0) scale(1.1)}}
/* The composition changes state as a whole. No independent ticker motion. */
.live[data-state="2"] .journal{grid-column:1/4;grid-row:1/3}.live[data-state="2"] .cafe{grid-column:4/6;grid-row:1/3}.live[data-state="2"] .prayer{grid-column:6/9;grid-row:1/3}.live[data-state="2"] .library{grid-column:3/9;grid-row:3/6}.live[data-state="2"] .one{grid-column:1/3;grid-row:3/5}.live[data-state="2"] .church{grid-column:1/3;grid-row:5/6}.live[data-state="3"] .journal{grid-column:1/3;grid-row:1/3}.live[data-state="3"] .cafe{grid-column:3/5;grid-row:1/3}.live[data-state="3"] .prayer{grid-column:5/7;grid-row:1/3}.live[data-state="3"] .library{grid-column:1/6;grid-row:3/6}.live[data-state="3"] .one{grid-column:7/9;grid-row:1/4}.live[data-state="3"] .church{grid-column:6/9;grid-row:4/6}.state-note{position:absolute;right:4.5vw;bottom:1.5vh;color:#cebd74}.current{position:absolute;left:4.5vw;bottom:1.5vh;color:#cebd74}
@media(max-width:760px){.field-head{grid-template-columns:1fr;height:27vh;gap:1vh}.field-head p{display:none}.composition{height:65vh;grid-template-columns:repeat(4,1fr);grid-template-rows:repeat(6,1fr);gap:8px}.journal{grid-column:1/5;grid-row:1/3}.cafe{grid-column:1/3;grid-row:3/4}.prayer{grid-column:3/5;grid-row:3/4}.library{grid-column:2/5;grid-row:4/7}.one{grid-column:1/2;grid-row:4/6}.church{grid-column:1/2;grid-row:6/7}.live[data-state] .journal{grid-column:1/5;grid-row:1/3}.live[data-state] .cafe{grid-column:1/3;grid-row:3/4}.live[data-state] .prayer{grid-column:3/5;grid-row:3/4}.live[data-state] .library{grid-column:2/5;grid-row:4/7}.live[data-state] .one{grid-column:1/2;grid-row:4/6}.live[data-state] .church{grid-column:1/2;grid-row:6/7}.unit .copy{left:12px;bottom:10px}.unit p{display:none}}@media(prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important}}
</style></head><body>'''+badge+'''<div class="progress"></div><main><section class="source"><div class="engrave"></div><div class="source-copy"><div class="micro goldtxt">Scripture Cinema · Source</div><h1>起初</h1><p>經文是入口。向下不是離開一張海報，而是進入同一條活水裡此刻最值得看的內容。</p></div><div class="down micro">SCROLL · INTO THE CURRENT</div></section><section class="live" id="live" data-state="1"><div class="stage"><header class="field-head"><div><span class="micro goldtxt">LIVE WEIGHTED EDITORIAL FIELD</span><h2>此刻，<br>值得看什麼。</h2></div><p>不是欄目目錄。不同世界的內容依照此刻的編輯權重，共同形成一張正在變化的版面。</p></header><div class="composition"><article class="unit journal"><span class="weight">03 · SLOW</span><div class="pulse"></div><div class="copy"><span class="micro">JOURNAL</span><h3>守望，<br>一座光明的城</h3><p>較重的內容佔據更多節拍，也在視野中停留更久。</p></div></article><article class="unit cafe"><span class="weight">01 · LIGHT</span><div class="copy"><span class="micro">DAYLIGHT CAFE</span><h3>Daylight Cafe</h3></div></article><article class="unit prayer"><span class="weight">01 · QUIET</span><div class="copy"><span class="micro">WATCH PRAYER</span><h3>守望禱告</h3></div></article><article class="unit library"><span class="weight">04 · HEAVY · HOLD</span><div class="pulse"></div><div class="copy"><span class="micro">DAWN LIBRARY</span><h3>黎明書局</h3><p>當權重增加，它不是跑到 Hero；它在原流中變重、擴張，周圍版面重新讓位。</p></div></article><article class="unit one"><span class="weight">02</span><div class="copy"><span class="micro">ONE</span><h3>查經</h3></div></article><article class="unit church"><span class="weight">01</span><div class="copy"><span class="micro">CHURCH</span><h3>Living Water</h3></div></article></div><div class="current micro">8:5 = RHYTHM, NOT CARD</div><div class="state-note micro" id="stateNote">COMPOSITION STATE 01</div></div></section></main><script>
const live=document.getElementById('live'),note=document.getElementById('stateNote');let last=1;function resolve(){const r=live.getBoundingClientRect(),span=Math.max(1,live.offsetHeight-innerHeight),p=Math.min(1,Math.max(0,-r.top/span));const s=p<.34?1:p<.68?2:3;if(s!==last){last=s;live.dataset.state=s;note.textContent='COMPOSITION STATE 0'+s}}addEventListener('scroll',resolve,{passive:true});resolve();
</script></body></html>'''
