"""New Westside Living Water Homepage — Design Candidate 02.
Turns the 8:5 vinyl-wall idea into a flowing, emergent spatial field.
"""
PAGE_ID='living-water-candidate-02'

def page():
    return {'id':PAGE_ID,'name':'Living Water · Candidate 02','canvas':{'w':1440,'h':960},'nodes':[],
      'design_experiment':{'schema':'dore.design-experiment.v1','track':'living-water-homepage','candidate':'02','status':'design-candidate','source_issue':531,
      'principles':['living-vinyl-wall','emergent-8:5-worlds','whole-page-flow','cross-current-parallax','confluence','temporal-hierarchy','viewport-conductor','enter-settle-return']}}

def install_workspace(base):
    original=base.workspace
    def workspace():
        w=original()
        if not any(p.get('id')==PAGE_ID for p in w.get('pages',[])):
            w['pages'].append(page());w=base.save(w)
        return w
    base.workspace=workspace

def install_editor(html):
    return html.replace("'living-water-candidate-01'])","'living-water-candidate-01','living-water-candidate-02'])")

def render(edit=False):
    badge='<div class="lab">DORÉ DESIGN · LIVING WATER · CANDIDATE 02</div>' if edit else ''
    return '''<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Living Water · Candidate 02</title><style>
*{box-sizing:border-box}html,body{margin:0;background:#07131d;color:#f7f1df;font-family:"Cormorant Garamond","Noto Serif TC",serif}body{overflow-x:hidden}.lab{position:fixed;z-index:1000;top:12px;left:12px;padding:7px 10px;background:#f4eddc;color:#111;font:10px ui-monospace,monospace;letter-spacing:.12em}.progress{position:fixed;z-index:999;left:0;top:0;width:100%;height:2px;background:#cebd74;transform-origin:left;animation:progress linear;animation-timeline:scroll(root block)}@keyframes progress{from{transform:scaleX(0)}to{transform:scaleX(1)}}
.source{height:108svh;position:relative;overflow:hidden;isolation:isolate;background:#07131d}.source:before{content:"";position:absolute;inset:-14%;background:radial-gradient(ellipse at 68% 38%,rgba(206,189,116,.4),transparent 27%),repeating-linear-gradient(164deg,transparent 0 12px,rgba(255,255,255,.055) 12px 13px),linear-gradient(118deg,#06101a 5%,#183547 56%,#987b28 130%);transform:scale(1.16);animation:sourceDrift linear both;animation-timeline:scroll(root block);animation-range:0 18%}.source:after{content:"";position:absolute;inset:auto -10% 0;height:36%;border-radius:50% 50% 0 0;background:linear-gradient(180deg,rgba(3,8,12,.02),#061016 70%);transform:rotate(-2deg)}.source-copy{position:absolute;z-index:3;left:6.5vw;bottom:10vh;width:min(760px,84vw)}.eyebrow,.micro{font:10px ui-monospace,monospace;letter-spacing:.18em;text-transform:uppercase;color:#cebd74}.source h1{font-size:clamp(72px,12vw,180px);font-weight:400;line-height:.72;margin:.12em 0}.source p{font-size:clamp(18px,1.65vw,25px);line-height:1.48;max-width:570px}@keyframes sourceDrift{from{transform:scale(1.2) translate3d(-3%,1%,0)}to{transform:scale(1.04) translate3d(5%,-3%,0)}}
.river-stage{position:relative;height:520svh;background:linear-gradient(180deg,#07131d 0%,#0f2a39 24%,#efe8d7 56%,#6f7d52 78%,#b8944a 100%)}.river-sticky{position:sticky;top:0;height:100svh;overflow:hidden;perspective:1500px}.water-lines{position:absolute;inset:0;pointer-events:none;opacity:.55;background:repeating-radial-gradient(ellipse at 50% 55%,transparent 0 38px,rgba(206,189,116,.13) 39px 40px);transform:scale(1.35) rotate(-4deg);animation:waterBreath 7s ease-in-out infinite alternate}@keyframes waterBreath{to{transform:scale(1.5) rotate(2deg) translateX(3vw)}}
.current{position:absolute;inset:0;will-change:transform}.current.a{animation:currentA linear both;animation-timeline:scroll(root block);animation-range:12% 78%}.current.b{animation:currentB linear both;animation-timeline:scroll(root block);animation-range:18% 84%}.current.c{animation:currentC linear both;animation-timeline:scroll(root block);animation-range:24% 90%}@keyframes currentA{from{transform:translate3d(22vw,18vh,0)}to{transform:translate3d(-128vw,-12vh,80px)}}@keyframes currentB{from{transform:translate3d(78vw,62vh,-120px)}to{transform:translate3d(-86vw,21vh,40px)}}@keyframes currentC{from{transform:translate3d(108vw,8vh,-220px)}to{transform:translate3d(-64vw,68vh,10px)}}
.vinyl{position:absolute;width:clamp(330px,43vw,650px);aspect-ratio:8/5;overflow:hidden;box-shadow:0 35px 110px rgba(0,0,0,.26);transform-origin:center;transition:filter .4s ease,opacity .4s ease;background:#111}.vinyl:before{content:"";position:absolute;inset:0;z-index:0}.vinyl .veil{position:absolute;inset:0;z-index:1;background:linear-gradient(90deg,rgba(5,10,14,.74),rgba(5,10,14,.08) 62%,rgba(5,10,14,.38))}.vinyl .copy{position:absolute;z-index:2;inset:auto 6% 8%;max-width:76%}.vinyl h2{font-size:clamp(38px,5.2vw,78px);font-weight:400;line-height:.86;margin:.12em 0}.vinyl p{font-size:clamp(13px,1.1vw,17px);line-height:1.42;max-width:380px}.vinyl.journal{left:12vw;top:12vh}.vinyl.journal:before{background:radial-gradient(circle at 70% 35%,rgba(206,189,116,.42),transparent 24%),repeating-linear-gradient(160deg,transparent 0 8px,rgba(255,255,255,.06) 8px 9px),linear-gradient(130deg,#07131d,#284c5d)}.vinyl.cafe{left:64vw;top:48vh;color:#1b1a16}.vinyl.cafe:before{background:radial-gradient(circle at 25% 25%,rgba(255,255,255,.62),transparent 23%),linear-gradient(140deg,#efe9da,#c7b987 58%,#7997a4)}.vinyl.cafe .veil{background:linear-gradient(90deg,rgba(245,239,224,.78),rgba(255,255,255,.04))}.vinyl.prayer{left:102vw;top:9vh}.vinyl.prayer:before{background:radial-gradient(circle at 30% 32%,rgba(246,241,223,.25),transparent 26%),linear-gradient(140deg,#324329,#71815a 60%,#17241c)}.vinyl.library{left:141vw;top:55vh;color:#18150e}.vinyl.library:before{background:repeating-linear-gradient(90deg,rgba(0,0,0,.09) 0 1px,transparent 1px 16px),linear-gradient(135deg,#d5c27a,#9e7b2b)}.vinyl.library .veil{background:linear-gradient(90deg,rgba(245,239,220,.8),rgba(255,255,255,.02))}.vinyl.dore{left:184vw;top:17vh}.vinyl.dore:before{background:repeating-radial-gradient(ellipse at 58% 48%,transparent 0 7px,rgba(255,255,255,.07) 7px 8px),linear-gradient(125deg,#111,#473c2f 55%,#c8ae5a)}
.vinyl:nth-child(2){animation:float1 6.4s ease-in-out infinite alternate}.vinyl:nth-child(3){animation:float2 8s ease-in-out infinite alternate}.vinyl:nth-child(4){animation:float3 7.2s ease-in-out infinite alternate}.vinyl:nth-child(5){animation:float2 9s ease-in-out infinite alternate}.vinyl:nth-child(6){animation:float1 7.8s ease-in-out infinite alternate}@keyframes float1{to{transform:translate3d(0,-2.5vh,28px) rotate(.7deg)}}@keyframes float2{to{transform:translate3d(1.8vw,2vh,48px) rotate(-.8deg)}}@keyframes float3{to{transform:translate3d(-1vw,-3vh,72px) rotate(.5deg)}}
.depth-mask{position:absolute;inset:0;pointer-events:none;background:radial-gradient(ellipse at center,transparent 0 44%,rgba(4,10,14,.14) 72%,rgba(4,10,14,.46));mix-blend-mode:multiply}.river-caption{position:absolute;z-index:20;left:5vw;top:7vh;max-width:440px}.river-caption h2{font-size:clamp(44px,6vw,90px);line-height:.85;font-weight:400;margin:.1em 0}.river-caption p{font-size:15px;line-height:1.45}.axis{position:absolute;z-index:25;right:2vw;top:50%;transform:rotate(90deg) translateX(50%);transform-origin:right top;font:10px ui-monospace,monospace;letter-spacing:.2em;color:#cebd74;mix-blend-mode:difference}
.confluence{min-height:115svh;background:#07131d;display:grid;grid-template-columns:1.1fr .9fr;align-items:center;gap:7vw;padding:10vw}.confluence h2{font-size:clamp(62px,10vw,150px);font-weight:400;line-height:.75;margin:0}.confluence p{font-size:clamp(18px,1.6vw,25px);line-height:1.5;max-width:560px}.confluence .pool{aspect-ratio:8/5;border-radius:50%;background:radial-gradient(ellipse at center,rgba(206,189,116,.32),rgba(42,79,94,.24) 35%,rgba(7,19,29,.05) 64%);filter:blur(.2px);animation:pool 5s ease-in-out infinite alternate}@keyframes pool{to{transform:scale(1.08) rotate(2deg)}}
@media(max-width:760px){.river-stage{height:440svh}.vinyl{width:74vw}.vinyl.journal{left:10vw}.vinyl.cafe{left:96vw}.vinyl.prayer{left:176vw}.vinyl.library{left:252vw}.vinyl.dore{left:330vw}.river-caption{left:6vw;right:6vw}.confluence{grid-template-columns:1fr;padding:15vh 7vw}.axis{display:none}}@media(prefers-reduced-motion:reduce){*{animation:none!important}.current{transform:none!important}.river-stage{height:auto}.river-sticky{position:relative;height:auto;display:grid;gap:8vw;padding:10vw}.current{position:relative;display:grid;gap:8vw}.vinyl{position:relative!important;left:auto!important;top:auto!important;width:100%;max-width:680px}.water-lines,.depth-mask{display:none}}
</style></head><body>'''+badge+'''<div class="progress"></div><section class="source"><div class="source-copy"><div class="eyebrow">Scripture Cinema · Source Current</div><h1>起初</h1><p>經文不是在上方播放完畢，然後網站才開始。它是水源；下面所有 8:5 世界都從同一個流場中被帶出。</p></div></section><section class="river-stage"><div class="river-sticky"><div class="water-lines"></div><div class="river-caption"><div class="micro">Living Vinyl Wall · Current Field</div><h2>不是牆。<br>是流場。</h2><p>8:5 不再逐張排隊。它們從不同深度、不同流速浮現、靠近、交錯、離開；前一個世界不會在下一個出現時立刻消失。</p></div><div class="axis">ONE RIVER · DIFFERENT CURRENTS</div><div class="current a"><article class="vinyl journal"><div class="veil"></div><div class="copy"><div class="micro">Journal</div><h2>守望，<br>一座光明的城</h2><p>深水層。慢速、厚重、版畫感。</p></div></article><article class="vinyl cafe"><div class="veil"></div><div class="copy"><div class="micro">Daylight Cafe</div><h2>Daylight<br>Cafe</h2><p>水面層。更快、更亮、更社交。</p></div></article></div><div class="current b"><article class="vinyl prayer"><div class="veil"></div><div class="copy"><div class="micro">Watch Prayer</div><h2>Watch<br>Prayer</h2><p>接近閱讀時減速，運動沉下來。</p></div></article><article class="vinyl library"><div class="veil"></div><div class="copy"><div class="micro">Dawn Library</div><h2>黎明書局</h2><p>像紙張、書脊與收藏秩序從河床浮出。</p></div></article></div><div class="current c"><article class="vinyl dore"><div class="veil"></div><div class="copy"><div class="micro">Doré</div><h2>Doré</h2><p>版畫線條成為更深一層的視覺暗流。</p></div></article></div><div class="depth-mask"></div></div></section><section class="confluence"><div><div class="micro">Confluence · Settle</div><h2>Living<br>Water</h2><p>真正的「活水」不是在背景畫波浪，而是讓內容本身具有流速、深度、匯流、浮現和沉降。這一版先把 8:5 黑膠牆從「排列」改造成「流場」。</p></div><div class="pool"></div></section></body></html>'''
