"""Living Water second-layer navigation lab.
Multiple content-semantic opening grammars; no single universal page transition.
"""
PAGE_ID='living-water-second-layer-lab'

def page():
    return {'id':PAGE_ID,'name':'Living Water · Second Layer Lab','canvas':{'w':1440,'h':960},'nodes':[],
      'design_experiment':{'schema':'dore.design-experiment.v1','track':'living-water-second-layer','status':'motion-lab',
      'grammars':['submerge','confluence','unfold','source','gather']}}

def install_workspace(base):
    original=base.workspace
    def workspace():
        w=original()
        if not any(p.get('id')==PAGE_ID for p in w.get('pages',[])):
            w['pages'].append(page());w=base.save(w)
        return w
    base.workspace=workspace

def install_editor(html):
    return html.replace("'living-water-candidate-02'])","'living-water-candidate-02','living-water-second-layer-lab'])")

def render(edit=False):
    badge='<div class="lab">DORÉ DESIGN · SECOND LAYER MOTION LAB</div>' if edit else ''
    return '''<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Living Water · Second Layer Lab</title><style>
*{box-sizing:border-box}html,body{margin:0;background:#07131d;color:#f7f1df;font-family:"Cormorant Garamond","Noto Serif TC",serif}body{min-height:100vh;overflow:hidden}.lab{position:fixed;z-index:99;top:12px;left:12px;padding:7px 10px;background:#f4eddc;color:#111;font:10px ui-monospace,monospace;letter-spacing:.12em}.head{position:fixed;z-index:20;left:5vw;top:7vh}.head h1{font-size:clamp(42px,6vw,82px);font-weight:400;line-height:.86;margin:.1em 0}.micro{font:10px ui-monospace,monospace;letter-spacing:.18em;text-transform:uppercase;color:#cebd74}.field{height:100vh;position:relative;perspective:1500px;background:radial-gradient(ellipse at 50% 55%,#183547 0,#07131d 58%)}.tile{position:absolute;width:min(34vw,510px);aspect-ratio:8/5;border:0;color:inherit;text-align:left;cursor:pointer;overflow:hidden;padding:0;box-shadow:0 25px 70px rgba(0,0,0,.28);transition:filter .35s,opacity .35s}.tile .art{position:absolute;inset:0}.tile .shade{position:absolute;inset:0;background:linear-gradient(0deg,rgba(3,8,12,.76),transparent 70%)}.tile .copy{position:absolute;z-index:2;left:7%;bottom:8%}.tile h2{font-size:clamp(30px,3.4vw,54px);font-weight:400;line-height:.88;margin:.12em 0}.library{left:8vw;top:38vh}.library .art{background:repeating-linear-gradient(90deg,rgba(0,0,0,.1) 0 1px,transparent 1px 15px),linear-gradient(135deg,#d4bf71,#896821)}.church{left:38vw;top:20vh}.church .art{background:radial-gradient(circle at 60% 28%,rgba(255,246,210,.36),transparent 22%),linear-gradient(135deg,#314b36,#71815a)}.journal{left:63vw;top:50vh}.journal .art{background:repeating-linear-gradient(160deg,transparent 0 8px,rgba(255,255,255,.06) 8px 9px),linear-gradient(130deg,#07131d,#31566a)}.scripture{left:68vw;top:10vh;width:min(27vw,420px)}.scripture .art{background:radial-gradient(circle at 65% 38%,rgba(206,189,116,.5),transparent 23%),repeating-radial-gradient(ellipse at 55% 50%,transparent 0 7px,rgba(255,255,255,.07) 7px 8px),#111}.one{left:28vw;top:66vh;width:min(27vw,420px)}.one .art{background:linear-gradient(140deg,#e9e2d2,#b5aa8c 52%,#5f7180)}
.world{position:fixed;z-index:50;inset:0;pointer-events:none;opacity:0;overflow:hidden}.world.open{pointer-events:auto;opacity:1}.world-bg{position:absolute;inset:0}.world-copy{position:absolute;z-index:4;left:7vw;bottom:9vh;max-width:720px}.world-copy h2{font-size:clamp(70px,12vw,170px);font-weight:400;line-height:.72;margin:.1em 0}.world-copy p{font-size:clamp(17px,1.5vw,23px);max-width:540px;line-height:1.45}.back{position:absolute;z-index:10;right:4vw;top:5vh;border:1px solid currentColor;background:transparent;color:inherit;padding:10px 14px;cursor:pointer;font:10px ui-monospace,monospace;letter-spacing:.15em}
.world[data-mode="unfold"]{background:#b8944a;color:#17130c;clip-path:inset(34% 44% 34% 44%)}.world[data-mode="unfold"].open{animation:unfold .9s cubic-bezier(.2,.8,.2,1) forwards}.world[data-mode="unfold"] .world-bg{background:repeating-linear-gradient(90deg,rgba(0,0,0,.08) 0 1px,transparent 1px 22px),linear-gradient(100deg,#d8c47b,#a07c2d)}@keyframes unfold{to{clip-path:inset(0 0 0 0)}}
.world[data-mode="submerge"]{background:#172a1c;transform:scale(.45);filter:blur(12px)}.world[data-mode="submerge"].open{animation:submerge .95s cubic-bezier(.15,.8,.15,1) forwards}.world[data-mode="submerge"] .world-bg{background:radial-gradient(circle at 55% 35%,rgba(255,244,204,.2),transparent 18%),linear-gradient(#647b58,#172a1c 70%)}@keyframes submerge{0%{transform:scale(.45) translateY(28vh);filter:blur(12px)}60%{filter:blur(0)}100%{transform:scale(1);filter:blur(0)}}
.world[data-mode="confluence"]{background:#07131d}.world[data-mode="confluence"] .world-bg{background:radial-gradient(circle at 50% 50%,rgba(206,189,116,.34),transparent 9%),radial-gradient(circle at 32% 35%,rgba(49,86,106,.7),transparent 22%),radial-gradient(circle at 72% 68%,rgba(111,125,82,.7),transparent 22%),#07131d;transform:scale(1.8)}.world[data-mode="confluence"].open .world-bg{animation:confluence 1.1s cubic-bezier(.2,.8,.2,1) forwards}@keyframes confluence{to{transform:scale(1) rotate(3deg)}}
.world[data-mode="source"]{background:#090b0c}.world[data-mode="source"] .world-bg{background:repeating-radial-gradient(ellipse at 50% 50%,transparent 0 10px,rgba(206,189,116,.09) 10px 11px),radial-gradient(circle at 50% 45%,#9d8132,#111 28%,#050607 70%);transform:scale(3)}.world[data-mode="source"].open .world-bg{animation:source 1.25s cubic-bezier(.16,.8,.2,1) forwards}@keyframes source{to{transform:scale(1)}}
.world[data-mode="gather"]{background:#eee7d8;color:#252525}.world[data-mode="gather"] .world-bg:before,.world[data-mode="gather"] .world-bg:after{content:"";position:absolute;width:42vw;aspect-ratio:8/5;top:18vh;background:linear-gradient(130deg,#78909c,#e8dfcb);box-shadow:0 25px 70px rgba(0,0,0,.16)}.world[data-mode="gather"] .world-bg:before{left:-30vw}.world[data-mode="gather"] .world-bg:after{right:-30vw}.world[data-mode="gather"].open .world-bg:before{animation:gatherL .9s ease forwards}.world[data-mode="gather"].open .world-bg:after{animation:gatherR .9s ease forwards}@keyframes gatherL{to{left:8vw;transform:rotate(-3deg)}}@keyframes gatherR{to{right:8vw;transform:rotate(3deg)}}
.legend{position:fixed;z-index:20;right:4vw;bottom:4vh;font:10px ui-monospace,monospace;letter-spacing:.1em;color:#cebd74}.field.dim .tile:not(.active){filter:blur(5px);opacity:.16;transform:scale(.92)}@media(max-width:760px){.tile{width:58vw}.library{left:5vw}.church{left:35vw}.journal{left:46vw}.scripture{left:58vw}.one{left:12vw}.head{top:8vh}.world-copy{left:7vw;right:7vw}}@media(prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important}.world.open{transform:none!important;filter:none!important;clip-path:none!important}}
</style></head><body>'''+badge+'''<div class="head"><div class="micro">Second Layer · Spatial Navigation Lab</div><h1>同一條河，<br>不同的入口。</h1></div><main class="field" id="field"><button class="tile library" data-mode="unfold" data-title="黎明書局"><div class="art"></div><div class="shade"></div><div class="copy"><div class="micro">Unfold · Publication</div><h2>黎明書局</h2></div></button><button class="tile church" data-mode="submerge" data-title="Living Water"><div class="art"></div><div class="shade"></div><div class="copy"><div class="micro">Submerge · Church</div><h2>Living Water</h2></div></button><button class="tile journal" data-mode="confluence" data-title="Journal"><div class="art"></div><div class="shade"></div><div class="copy"><div class="micro">Confluence · Editorial</div><h2>Journal</h2></div></button><button class="tile scripture" data-mode="source" data-title="Scripture"><div class="art"></div><div class="shade"></div><div class="copy"><div class="micro">Source · Scripture</div><h2>Scripture</h2></div></button><button class="tile one" data-mode="gather" data-title="ONE"><div class="art"></div><div class="shade"></div><div class="copy"><div class="micro">Gather · Research</div><h2>ONE</h2></div></button></main><div class="legend">CLICK EACH 8:5 WORLD · COMPARE NAVIGATION GRAMMARS</div><section class="world" id="world"><div class="world-bg"></div><button class="back" id="back">RETURN TO RIVER</button><div class="world-copy"><div class="micro" id="mode"></div><h2 id="title"></h2><p id="desc"></p></div></section><script>
const field=document.getElementById('field'),world=document.getElementById('world'),title=document.getElementById('title'),mode=document.getElementById('mode'),desc=document.getElementById('desc');
const descriptions={unfold:'出版物不是被打開，而是從封面展開。8:5 的邊界向外解鎖，書頁、索引與收藏空間從原來的 cover 內部延伸。',submerge:'教會不是另一張 publication page。入口向深處沉入，從水面進入聚會、共同體與敬拜的內部空間。',confluence:'Journal 以匯流進入：相關內容不是推薦卡，而是被同一主題吸引到一起，形成新的 editorial field。',source:'Scripture 不是向前翻頁，而是逆流尋源。視野向源頭收束，回到經文、章節與 Scripture Cinema。',gather:'ONE 以研究聚合進入：散落的證據、經文與工具從兩側聚集，形成可工作的研究桌面。'};
document.querySelectorAll('.tile').forEach(t=>t.addEventListener('click',()=>{document.querySelectorAll('.tile').forEach(x=>x.classList.remove('active'));t.classList.add('active');field.classList.add('dim');world.dataset.mode=t.dataset.mode;title.textContent=t.dataset.title;mode.textContent=t.dataset.mode.toUpperCase()+' · SECOND LAYER';desc.textContent=descriptions[t.dataset.mode];world.classList.remove('open');void world.offsetWidth;world.classList.add('open')}));
document.getElementById('back').addEventListener('click',()=>{world.classList.remove('open');field.classList.remove('dim');document.querySelectorAll('.tile').forEach(x=>x.classList.remove('active'))});
</script></body></html>'''
