#!/usr/bin/env python3
"""Generate semantic, scoped CSS from the single Westside Design OS token source."""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
TOKENS = ROOT / "design-system/tokens/westside.tokens.json"
SCOPES = ROOT / "design-system/scopes.json"
OUTPUT = ROOT / "static/css/westside-design-tokens.css"

def css_value(item):
    kind, value = item["$type"], item["$value"]
    if kind == "fontFamily":
        return ", ".join(x if x in ("serif", "sans-serif", "monospace") else json.dumps(x, ensure_ascii=False) for x in value)
    if kind == "color":
        if value.get("colorSpace") != "srgb" or len(value["components"]) != 3:
            raise ValueError("Only three-channel sRGB color is supported")
        return "#" + "".join(f"{round(x * 255):02x}" for x in value["components"])
    if kind == "fontWeight":
        return str(int(value))
    if kind in ("dimension", "string"):
        return str(value)
    raise ValueError("Unsupported token type: " + kind)

def create():
    tokens = json.loads(TOKENS.read_text())
    scopes = json.loads(SCOPES.read_text())["scopes"]
    declarations = []
    for group in ("font", "weight", "color"):
        for name, value in tokens[group].items():
            prefix = {"font": "type", "weight": "weight", "color": ""}[group]
            css_name = "--ws-" + (prefix + "-" if prefix else "") + name
            declarations.append(f"  {css_name}: {css_value(value)};")
    # Existing semantic consumers keep these stable aliases during migration.
    for name in ("display-en", "display-en-sc", "display-zh", "reading-zh"):
        declarations.append(f"  --ws-os-font-{name}: var(--ws-type-{name});")
    lines = ["/* Generated by scripts/build_westside_design_os.py — do not edit. */",
             ":root {", *declarations, "}", ""]
    overrides = tokens.get("overrides", {})
    for scope, settings in overrides.items():
        if scope == "global" or scope not in scopes:
            raise ValueError("Invalid scoped override: " + scope)
        selector = scopes[scope]["selector"]
        if not selector.startswith("[data-ws-scope="):
            raise ValueError("Unsafe selector for " + scope)
        lines.append(selector + " {")
        for token_name, value in sorted(settings.items()):
            if not token_name.startswith("--ws-") or any(x in token_name for x in (";", "{", "}")):
                raise ValueError("Invalid scoped CSS variable")
            if not isinstance(value, str) or any(x in value for x in (";", "{", "}")):
                raise ValueError("Invalid scoped CSS value")
            lines.append(f"  {token_name}: {value};")
        lines.append("}")
    return "\n".join(lines) + "\n"

if __name__ == "__main__":
    generated = create()
    if "--check" in sys.argv:
        if not OUTPUT.exists() or OUTPUT.read_text() != generated:
            sys.exit("Westside Design OS tokens are out of date")
        print("Westside Design OS generated tokens: PASS")
    else:
        OUTPUT.write_text(generated)
        print("Generated", OUTPUT.relative_to(ROOT))
