#!/usr/bin/env python3
"""Deployment gate for public resource records and all book surfaces."""
import json,sys
from pathlib import Path
from resource_selection import ROOT,POLICY,REVIEWS,excluded,book_allowed

def check(root=ROOT):
    failures=[]
    catalog=json.loads((root/'static/dawn-library/biblical-world/catalog.json').read_text())
    store=json.loads((root/'static/dawn-library/storefront.json').read_text())
    books=catalog['items']+[i for s in store['shelves'] for i in s['items']]
    for item in books:
        if not book_allowed(item):failures.append('unadmitted book: '+str(item.get('id')))
    if store['metrics']['mappedBooks']!=sum(len(s['items']) for s in store['shelves']):failures.append('book-count mismatch')
    def scan(value,path):
        if isinstance(value,list):
            for item in value:scan(item,path)
        elif isinstance(value,dict):
            is_resource=any(k in value for k in ('sourceUrl','sources','source','url','work')) and any(k in value for k in ('title','name','work'))
            if is_resource and excluded(value):failures.append('excluded public resource: '+str(path.relative_to(root)))
            for item in value.values():scan(item,path)
    for parent in ('data','static'):
        for path in (root/parent).rglob('*.json'):
            if path.name.startswith('resource_'):continue
            try:scan(json.loads(path.read_text()),path)
            except (UnicodeError,json.JSONDecodeError):continue  # Not every legacy JSON-looking asset is a resource index.
    for name in ('discovery-candidates','relevance-results','english-resolver-results','chinese-candidates','chinese-relevance-results','chinese-resolver-results'):
        if (root/f'static/dawn-library/biblical-world/{name}.json').exists():failures.append('public review queue: '+name)
    expected='// Generated by scripts/sync_resource_selection.py; edit data/resource_* instead.\n'
    expected+='export const policy='+json.dumps(POLICY,ensure_ascii=False,separators=(',',':'))+';\n'
    expected+='export const reviews='+json.dumps(REVIEWS,ensure_ascii=False,separators=(',',':'))+';\n'
    if (root/'static/resources/selection-data.mjs').read_text()!=expected:failures.append('browser policy out of sync')
    if failures:raise AssertionError('\n'.join(failures))
    print(f'PASS: {len(catalog["items"])} catalog books; {store["metrics"]["mappedBooks"]} storefront books; no public review queues; shared policy in sync')
if __name__=='__main__':check()
