#!/usr/bin/env python3
"""Generate the browser copy from the authoritative versioned policy/reviews."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
policy=json.loads((ROOT/'data/resource_selection_policy.json').read_text())
reviews=json.loads((ROOT/'data/resource_book_reviews.json').read_text())['items']
output='// Generated by scripts/sync_resource_selection.py; edit data/resource_* instead.\n'
output+='export const policy='+json.dumps(policy,ensure_ascii=False,separators=(',',':'))+';\n'
output+='export const reviews='+json.dumps(reviews,ensure_ascii=False,separators=(',',':'))+';\n'
(ROOT/'static/resources/selection-data.mjs').write_text(output)
