#!/usr/bin/env python3
"""Static production acceptance for the Doré Bible Search external work node."""
from __future__ import annotations
import json
from pathlib import Path
OUT=Path('reports/DORÉ-BIBLE-SEARCH-WORK-NODE.json')
def check(condition,label,failures):
    if not condition:failures.append(label)
def main():
    failures=[]
    page=Path('static/dore/search/index.html').read_text(encoding='utf-8')
    redirect=Path('static/dore/index.html').read_text(encoding='utf-8')
    js=Path('static/dore/dore-search.js').read_text(encoding='utf-8')
    gallery=Path('static/dore/dore-gallery.js').read_text(encoding='utf-8')
    intelligence=Path('static/dore/dore-bible-intelligence.js').read_text(encoding='utf-8')
    open_crossrefs=Path('static/dore/dore-open-crossrefs.js').read_text(encoding='utf-8')
    join=Path('join/index.html').read_text(encoding='utf-8')
    one_js=Path('static/one/one-opening-simple.js').read_text(encoding='utf-8')
    one_crossref=Path('static/one/one-cross-reference-scripture-global-audit.js').read_text(encoding='utf-8')
    one_crossref_ui=Path('static/one/one-dore-crossref-ui.js').read_text(encoding='utf-8')
    one_crossref_ui_css=Path('static/one/one-dore-crossref-ui.css').read_text(encoding='utf-8')
    one_css=Path('static/one/one-opening-simple.css').read_text(encoding='utf-8')
    home=Path('layouts/index.html').read_text(encoding='utf-8')
    assets=Path('static/one/one-dore-assets-241.js').read_text(encoding='utf-8')
    core_path=Path('static/dore/search-index.json');orig_path=Path('static/dore/original-index.json')
    manifest_path=Path('static/dore/crossrefs/manifest.json')
    core=json.loads(core_path.read_text(encoding='utf-8'));orig=json.loads(orig_path.read_text(encoding='utf-8'))
    manifest=json.loads(manifest_path.read_text(encoding='utf-8')) if manifest_path.exists() else {}
    check(core.get('schema')=='dore.browser-search-core.v1','core_schema',failures)
    check(orig.get('schema')=='dore.browser-original-index.v1','original_schema',failures)
    check(len(core.get('verses',[]))>=31000,'verse_coverage',failures)
    refs={v['r']:v for v in core.get('verses',[])}
    check('bible.ref.JHN.3.16' in refs,'john_3_16',failures);check('bible.ref.JER.33.3' in refs,'jeremiah_33_3',failures)
    check(bool(orig.get('lemma')) and bool(orig.get('morphology')),'original_language_indexes',failures)
    check('rgba(206,189,116,.78)' in page and ("url('/background.jpg')" in page or 'SITE-BACKGROUND' in page),'join_background_contract',failures)
    check('耶利米書 33:3' in page,'search_verse',failures)
    check('byChapter' in js and "kind:'chapter'" in js and 'chapter-reading' in page,'chapter_reference_ui',failures)
    check('/dore/original-index.json' in js and 'ensureOriginal' in js,'lazy_original_index',failures)
    check('one-dore-assets-241.js' in page and 'Array.from({length:241}' in gallery and '241-complete' in assets,'dore_241_original_archive',failures)
    check('/dore/search/' in redirect,'root_redirect_to_search',failures)
    check('href="/dore/search/"' in join,'join_direct_search_entry',failures)
    check('dore-inline-search' in one_js and 'location.href="/dore/search/?q="' in one_js,'one_direct_visible_search_entry',failures)
    check('data-dore-search-entry' in home and 'dore-inline-search' in home and '/dore/dore-search-entry.js' in home,'main_site_direct_search_entry',failures)
    check('dore-bible-intelligence.js' in gallery and 'intelligenceRuntime.async=false' in gallery,'search2_runtime_loaded_before_brain',failures)
    check('DoreBibleIntelligence' in intelligence and 'ingestScriptureThreads' in intelligence and 'related(ref,opts={})' in intelligence,'shared_bible_intelligence_graph',failures)
    check('crossReferenceShared' in one_js and 'shared.related' in one_js and 'shared.query' in one_js,'one_consumes_shared_bible_intelligence',failures)
    check('gilead-jabesh-saul' in intelligence and 'wilderness-temptation-deuteronomy' in intelligence and 'ot-spirit-false-premise' in intelligence,'search2_semantic_reflexes',failures)
    stats=manifest.get('stats',{})
    check(manifest.get('schema')=='dore.crossrefs.manifest.v1','open_crossrefs_manifest_schema',failures)
    check(manifest.get('source_dataset')=='neuu-bible-crossrefs','open_crossrefs_dataset',failures)
    check(manifest.get('license')=='CC BY 4.0' and manifest.get('contains_bible_text') is False,'open_crossrefs_provenance_license',failures)
    check(int(stats.get('directed_edges',0))>=1_000_000,'open_crossrefs_million_edge_coverage',failures)
    check(int(stats.get('unique_verses',0))>=30_000,'open_crossrefs_verse_coverage',failures)
    check(int(stats.get('books',0))>=60,'open_crossrefs_canon_coverage',failures)
    check(len(list(Path('static/dore/crossrefs').glob('*.json')))>=61,'open_crossrefs_shards',failures)
    check('relatedAsync' in open_crossrefs and 'traceOpenCrossref' in open_crossrefs and 'CC BY 4.0' not in open_crossrefs,'open_crossrefs_lazy_runtime',failures)
    check('dore-open-crossrefs.js' in gallery,'search_consumes_open_crossrefs',failures)
    check('shared.relatedAsync' in one_crossref and 'shared.openRelated' in one_crossref and 'shared.trace' in one_crossref and 'dore-open-crossrefs.js' in one_crossref,'one_consumes_open_crossrefs',failures)
    check('one-dore-crossref-ui.js' in one_js and 'one-dore-crossref-ui.css' in one_js,'one_crossref_ui_loader',failures)
    check('百萬串珠圖' in one_crossref_ui and 'source_votes' in one_crossref_ui and 'relatedAsync' in one_crossref_ui and '查看關係路徑與來源' in one_crossref_ui,'one_visible_crossref_intelligence',failures)
    check('dore-crossref-results' in one_crossref_ui_css and '@media(max-width:780px)' in one_crossref_ui_css,'one_crossref_ui_responsive',failures)
    verdict='PASS' if not failures else 'FAIL'
    result={'schema':'dore.work-node.bible-search.v4','verdict':verdict,'work_node':'DORE_BIBLE_SEARCH','status':'AVAILABLE' if verdict=='PASS' else 'NOT_READY','function_url':'/dore/search/','failures':failures,'entrances':['JOIN','ONE','WESTSIDE_WATCH_MAIN'],'capabilities':['canonical_reference','chapter_reference','cuv_webu_keyword','fuzzy_recall_candidates','original_surface','lemma','morphology','provenance_display','dore_original_archive_241','shared_bible_intelligence_graph','weighted_multi_hop_relations','semantic_study_intents','one_shared_intelligence_bridge','neuu_openbible_tsk_crossrefs','million_edge_crossref_graph','lazy_book_crossref_shards','traceable_open_crossrefs','one_open_crossref_bridge','one_visible_crossref_graph_ui','crossref_source_vote_weight_ui','crossref_multihop_trace_ui'],'crossrefs':stats,'performance':{'core_index_bytes':core_path.stat().st_size,'original_index_bytes':orig_path.stat().st_size,'crossrefs_manifest_bytes':manifest_path.stat().st_size if manifest_path.exists() else 0,'original_index_loading':'lazy','crossrefs_loading':'lazy_by_source_book','dore_archive_loading':'two-slot_lazy_cycle'},'governance':'External work-node acceptance. Open cross-reference capability must be backed by the generated NEUU/OpenBible+TSK corpus with traceable CC BY 4.0 provenance; ONE must expose the graph visibly with source/vote/weight/path controls. This is still not completion of permanent issue #281.'}
    OUT.parent.mkdir(parents=True,exist_ok=True);OUT.write_text(json.dumps(result,ensure_ascii=False,indent=2,sort_keys=True)+'\n',encoding='utf-8');print(json.dumps(result,ensure_ascii=False,indent=2))
    if verdict!='PASS':raise SystemExit(1)
if __name__=='__main__':main()
