import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';

const EVIDENCE_COLORS={observed:0x78806b,reconstructed:0xb49b70,inferred:0x9d8e79,disputed:0x8e665c};
function evidenceClass(value=''){if(value.includes('disputed'))return'disputed';if(value.includes('observed')||value.includes('archaeological'))return'observed';if(value.includes('reconstructed')||value.includes('textual'))return'reconstructed';return'inferred'}
function dimensionsFor(kind){return({
  'platform-enclosure':[520,340,34],
  'portico-basilica':[390,70,70],
  fortress:[150,150,150],
  'sacred-complex':[210,160,125],
  'pilgrimage-access':[190,95,22],
  street:[55,300,8]
}[kind]||[90,90,55])}

// Source runtime authority: threejs-architecture-effects scene/camera/control pattern.
// Jerusalem geometry authority comes only from evidence ledgers; withheld objects are never invented.
export function mountJerusalemThreeScene(mount,{onReady}={}){
  const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(34,1,.1,18000);camera.position.set(3800,2250,5700);
  const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<700?1.5:2));renderer.setClearColor(0xf4f1e9,0);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.shadowMap.autoUpdate=false;mount.replaceChildren(renderer.domElement);
  scene.add(new THREE.HemisphereLight(0xfaf7ef,0x706a5c,.72));const key=new THREE.DirectionalLight(0xfff2e2,2.4);key.position.set(-2200,3800,3000);key.castShadow=true;key.shadow.mapSize.set(2048,2048);key.shadow.camera.left=-4500;key.shadow.camera.right=4500;key.shadow.camera.top=4500;key.shadow.camera.bottom=-4500;key.shadow.camera.near=50;key.shadow.camera.far=12000;key.shadow.normalBias=.025;key.shadow.bias=-.00015;key.shadow.radius=3;key.target.position.set(0,0,0);scene.add(key,key.target);const fill=new THREE.DirectionalLight(0xe5eced,.55);fill.position.set(2500,1800,-1000);scene.add(fill);const rim=new THREE.DirectionalLight(0xfff4de,.7);rim.position.set(-1200,3000,-2400);scene.add(rim);
  const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,0,0);controls.enableDamping=true;controls.dampingFactor=.075;controls.enablePan=true;controls.minDistance=700;controls.maxDistance=11000;controls.minPolarAngle=.35;controls.maxPolarAngle=Math.PI*.51;controls.autoRotate=true;controls.autoRotateSpeed=.32;
  const root=new THREE.Group();root.name='jerusalem-temporal-city';scene.add(root);const terrain=new THREE.Mesh(new THREE.PlaneGeometry(7600,7600,48,48),new THREE.MeshStandardMaterial({color:0xc8b99e,roughness:.96,metalness:0}));terrain.rotation.x=-Math.PI/2;terrain.receiveShadow=true;terrain.name='terrain-pending-canonical-dem';root.add(terrain);
  const historical=new THREE.Group();historical.name='historical-evidence-geometry';root.add(historical);const pieces=[];
  function addEvidencePiece(object){if(!object.spatial?.enuMetres||object.spatial.registration==='withheld'||object.geometry?.status==='withheld')return;const [w,d,h]=dimensionsFor(object.kind),klass=evidenceClass(object.evidence),mat=new THREE.MeshStandardMaterial({color:EVIDENCE_COLORS[klass],roughness:.9,metalness:0,transparent:klass==='disputed',opacity:klass==='disputed'?.66:1});const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);const east=object.spatial.enuMetres.east||0,north=object.spatial.enuMetres.north||0;mesh.position.set(east,h/2,-north);mesh.castShadow=true;mesh.receiveShadow=true;mesh.name=object.id;mesh.userData={evidence:object.evidence,confidence:object.confidence,registration:object.spatial.registration,build:{start:.44,duration:.055,lift:180},baseY:h/2};mesh.visible=false;historical.add(mesh);pieces.push(mesh)}
  fetch('./data/objects/herodian-30ce.json').then(r=>{if(!r.ok)throw new Error('Herodian evidence ledger unavailable');return r.json()}).then(ledger=>{ledger.objects.forEach(addEvidencePiece);renderer.shadowMap.needsUpdate=true}).catch(err=>{console.error('[J3K] evidence geometry',err)});
  function setBuildProgress(v){const progress=Math.max(0,Math.min(1,v));for(const mesh of pieces){const b=mesh.userData.build,t=Math.max(0,Math.min(1,(progress-b.start)/b.duration));mesh.visible=t>0;if(!mesh.visible)continue;const settle=Math.sin(t*Math.PI*2)*(1-t)*(1-t)*.035;mesh.position.y=mesh.userData.baseY+b.lift*((1-t)**3-settle)}}
  let needsFrame=true,lastNow=performance.now(),raf=0;controls.addEventListener('change',()=>{needsFrame=true});const resize=()=>{const w=Math.max(1,mount.clientWidth),h=Math.max(1,mount.clientHeight);renderer.setSize(w,h,false);camera.aspect=w/h;camera.fov=camera.aspect<.58?39:34;camera.updateProjectionMatrix();needsFrame=true};const ro=new ResizeObserver(resize);ro.observe(mount);resize();function render(now){const dt=Math.min((now-lastNow)/1000,.1);lastNow=now;const changed=controls.update(dt);if(!document.hidden&&(needsFrame||changed||controls.autoRotate)){renderer.shadowMap.needsUpdate=true;renderer.render(scene,camera);needsFrame=false}raf=requestAnimationFrame(render)}raf=requestAnimationFrame(render);onReady?.();return{scene,camera,renderer,controls,root,setBuildProgress,dispose(){cancelAnimationFrame(raf);ro.disconnect();controls.dispose();terrain.geometry.dispose();terrain.material.dispose();for(const p of pieces){p.geometry.dispose();p.material.dispose()}renderer.dispose();renderer.domElement.remove()}};
}