import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {HeritageBuilder} from './heritage-builder.js';
import {addEvidenceArchitecture} from './jerusalem-architecture.js';

const EVIDENCE_COLORS={observed:0x78806b,reconstructed:0xb49b70,inferred:0x9d8e79,disputed:0x8e665c};
function makeMaterials(){const out={};for(const [name,color] of Object.entries(EVIDENCE_COLORS))out[name]=new THREE.MeshStandardMaterial({color,roughness:.9,metalness:0,transparent:name==='disputed',opacity:name==='disputed'?.66:1,vertexColors:true});return out;}

// Camera/control and HeritageBuilder -> aBuild -> uBuildProgress construction grammar
// are ported from threejs-architecture-effects. Jerusalem evidence ledgers alone decide what exists.
export function mountJerusalemThreeScene(mount,{onReady}={}){
  const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(34,1,.1,18000);camera.position.set(3800,2250,5700);
  const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<700?1.5:2));renderer.setClearColor(0xf4f1e9,0);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.shadowMap.autoUpdate=false;mount.replaceChildren(renderer.domElement);
  scene.add(new THREE.HemisphereLight(0xfaf7ef,0x706a5c,.72));const key=new THREE.DirectionalLight(0xfff2e2,2.4);key.position.set(-2200,3800,3000);key.castShadow=true;key.shadow.mapSize.set(2048,2048);key.shadow.camera.left=-4500;key.shadow.camera.right=4500;key.shadow.camera.top=4500;key.shadow.camera.bottom=-4500;key.shadow.camera.near=50;key.shadow.camera.far=12000;key.shadow.normalBias=.025;key.shadow.bias=-.00015;key.shadow.radius=3;key.target.position.set(0,0,0);scene.add(key,key.target);const fill=new THREE.DirectionalLight(0xe5eced,.55);fill.position.set(2500,1800,-1000);scene.add(fill);const rim=new THREE.DirectionalLight(0xfff4de,.7);rim.position.set(-1200,3000,-2400);scene.add(rim);
  const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,0,0);controls.enableDamping=true;controls.dampingFactor=.075;controls.enablePan=true;controls.minDistance=700;controls.maxDistance=11000;controls.minPolarAngle=.35;controls.maxPolarAngle=Math.PI*.51;controls.autoRotate=true;controls.autoRotateSpeed=.32;
  const root=new THREE.Group();root.name='jerusalem-temporal-city';scene.add(root);const terrain=new THREE.Mesh(new THREE.PlaneGeometry(7600,7600,48,48),new THREE.MeshStandardMaterial({color:0xc8b99e,roughness:.96,metalness:0}));terrain.rotation.x=-Math.PI/2;terrain.receiveShadow=true;terrain.name='terrain-pending-canonical-dem';root.add(terrain);
  const historical=new THREE.Group();historical.name='historical-evidence-geometry';root.add(historical);const materials=makeMaterials(),builder=new HeritageBuilder(materials);let currentProgress=0,renderableObjects=0;
  function setBuildProgress(v){currentProgress=Math.max(0,Math.min(1,v));builder.setProgress(currentProgress);renderer.shadowMap.needsUpdate=true;}
  const ready=fetch('./data/objects/herodian-30ce.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`Herodian evidence ledger unavailable (${r.status})`);return r.json()}).then(ledger=>{if(!Array.isArray(ledger.objects)||!ledger.objects.length)throw new Error('Herodian evidence ledger empty');for(const object of ledger.objects)if(addEvidenceArchitecture(builder,object))renderableObjects++;if(!renderableObjects)throw new Error('No renderable evidence geometry after withheld policy');builder.finish(historical);setBuildProgress(currentProgress);renderer.shadowMap.needsUpdate=true;onReady?.({renderableObjects,ledgerObjects:ledger.objects.length,constructionPieces:builder.pieces,assemblyRuntime:'HeritageBuilder/aBuild/uBuildProgress'});return{renderableObjects,ledgerObjects:ledger.objects.length,constructionPieces:builder.pieces}});
  let needsFrame=true,lastNow=performance.now(),raf=0;controls.addEventListener('change',()=>{needsFrame=true});const resize=()=>{const w=Math.max(1,mount.clientWidth),h=Math.max(1,mount.clientHeight);renderer.setSize(w,h,false);camera.aspect=w/h;camera.fov=camera.aspect<.58?39:34;camera.updateProjectionMatrix();needsFrame=true};const ro=new ResizeObserver(resize);ro.observe(mount);resize();function render(now){const dt=Math.min((now-lastNow)/1000,.1);lastNow=now;const changed=controls.update(dt);if(!document.hidden&&(needsFrame||changed||controls.autoRotate)){renderer.shadowMap.needsUpdate=true;renderer.render(scene,camera);needsFrame=false}raf=requestAnimationFrame(render)}raf=requestAnimationFrame(render);return{scene,camera,renderer,controls,root,ready,setBuildProgress,dispose(){cancelAnimationFrame(raf);ro.disconnect();controls.dispose();builder.dispose();Object.values(materials).forEach(m=>m.dispose());terrain.geometry.dispose();terrain.material.dispose();renderer.dispose();renderer.domElement.remove()}};
}
