import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {HeritageBuilder} from './heritage-builder.js';
import {addEvidenceArchitecture} from './jerusalem-architecture.js';
import {EvidenceResolutionEngine} from './evidence-resolution-engine.js';
import {auditEvidenceResolution} from './evidence-resolution-audit.js';
import {loadTerrainAuthority,loadCanonicalTerrain} from './terrain-runtime.js';
import {auditSpatialRegistrations} from './spatial-registration-audit.js';
import {auditArchitecturalGrammar,auditArchitecturalPieceDensity} from './architectural-grammar-audit.js';
const EVIDENCE_COLORS={observed:0x78806b,reconstructed:0xb49b70,inferred:0x9d8e79,disputed:0x8e665c};
const TEMPORAL_COLORS={observed:0x8d8069,reconstructed:0xb49b70,inferred:0xa99b84,disputed:0x8e665c};
function makeMaterials(){const out={};for(const[name,color]of Object.entries(EVIDENCE_COLORS))out[name]=new THREE.MeshStandardMaterial({color,roughness:.9,metalness:0,transparent:true,opacity:name==='disputed'?.66:1,vertexColors:true});return out}
function temporalEvidence(object){const e=String(object.evidence||'').toLowerCase();if(e.includes('disputed'))return'disputed';if(e.includes('observed')||e.includes('archaeological'))return'observed';if(e.includes('reconstructed')||e.includes('textual'))return'reconstructed';return'inferred'}
function temporalShape(object,index){const seed=[...object.id].reduce((n,c)=>((n*31+c.charCodeAt(0))>>>0),2166136261);const angle=((seed%6283)/1000),radius=280+(seed%1450),x=Math.cos(angle)*radius,z=Math.sin(angle)*radius;const kind=object.kind||'';let w=180,d=150,h=90;if(kind.includes('wall')||kind.includes('fortification')){w=620;d=42;h=115}if(kind.includes('gate')){w=150;d=90;h=170}if(kind.includes('sanctuary')){w=330;d=250;h=190}if(kind.includes('urban-envelope')){w=720;d=560;h=38}if(kind.includes('urban-fabric')){w=520;d=430;h=55}if(kind.includes('transport')){w=760;d=24;h=10}if(kind.includes('water')){w=300;d=55;h=55}if(kind.includes('monumental')){w=360;d=280;h=145}return{x:x+(index%3)*45,z:z+((index*73)%190)-95,w,d,h,rotation:angle*.35}}
export function mountJerusalemThreeScene(mount,{onReady}={}){
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(34,1,.1,18000);camera.position.set(3800,2250,5700);const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;const coarsePointer=matchMedia('(pointer: coarse)').matches;const pixelRatio=Math.min(devicePixelRatio,coarsePointer?1.25:1.75);renderer.setPixelRatio(pixelRatio);renderer.setClearColor(0xf4f1e9,0);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1;renderer.shadowMap.enabled=!coarsePointer;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.shadowMap.autoUpdate=false;mount.replaceChildren(renderer.domElement);
 scene.add(new THREE.HemisphereLight(0xfaf7ef,0x706a5c,.72));const key=new THREE.DirectionalLight(0xfff2e2,2.4);key.position.set(-2200,3800,3000);key.castShadow=!coarsePointer;key.shadow.mapSize.set(coarsePointer?1024:2048,coarsePointer?1024:2048);key.shadow.camera.left=-4500;key.shadow.camera.right=4500;key.shadow.camera.top=4500;key.shadow.camera.bottom=-4500;key.shadow.camera.near=50;key.shadow.camera.far=12000;key.shadow.normalBias=.025;key.shadow.bias=-.00015;key.shadow.radius=3;key.target.position.set(0,0,0);scene.add(key,key.target);const fill=new THREE.DirectionalLight(0xe5eced,.55);fill.position.set(2500,1800,-1000);scene.add(fill);const rim=new THREE.DirectionalLight(0xfff4de,.7);rim.position.set(-1200,3000,-2400);scene.add(rim);
 const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,120,0);controls.enableDamping=true;controls.dampingFactor=.075;controls.enablePan=true;controls.minDistance=700;controls.maxDistance=11000;controls.minPolarAngle=.35;controls.maxPolarAngle=Math.PI*.51;controls.autoRotate=!reducedMotion;controls.autoRotateSpeed=.32;
 const root=new THREE.Group();root.name='jerusalem-temporal-city';scene.add(root);const historical=new THREE.Group();historical.name='herodian-evidence-geometry';root.add(historical);const temporalLayer=new THREE.Group();temporalLayer.name='anchor-era-temporal-layer';root.add(temporalLayer);const materials=makeMaterials(),builder=new HeritageBuilder(materials),temporalMaterials={};for(const[name,color]of Object.entries(TEMPORAL_COLORS))temporalMaterials[name]=new THREE.MeshStandardMaterial({color,roughness:.94,transparent:true,opacity:name==='disputed'?.5:.82});let currentProgress=0,currentRuin=0,renderableObjects=0,terrainRuntime=null,evidenceResolution=null,currentEvidenceMode='all',currentPhaseId='';const temporalMeshes=new Map();
 function herodianPhaseActive(){return currentPhaseId==='herodian'||currentPhaseId==='roman-destruction'}
 function applyTemporalState(){builder.setProgress(herodianPhaseActive()?currentProgress:0);historical.visible=herodianPhaseActive();historical.position.y=-18*currentRuin;historical.rotation.z=.006*currentRuin;historical.scale.y=1-.42*currentRuin;for(const m of builder.meshes){m.material.opacity=(m.material.name==='disputed'?.66:1)*(1-.32*currentRuin)}if(renderer.shadowMap.enabled)renderer.shadowMap.needsUpdate=true}
 function setBuildProgress(v){currentProgress=Math.max(0,Math.min(1,v));applyTemporalState()}
 function setRuinProgress(v){currentRuin=Math.max(0,Math.min(1,v));applyTemporalState()}
 function evidenceAllowed(level){if(currentEvidenceMode==='all')return true;if(currentEvidenceMode==='observed')return level==='observed';if(currentEvidenceMode==='reconstructed')return level==='observed'||level==='reconstructed';if(currentEvidenceMode==='inferred')return level!=='disputed';return level==='disputed'}
 function setEvidenceMode(mode='all'){currentEvidenceMode=mode;if(evidenceResolution)for(const mesh of builder.meshes){const object=mesh.userData?.evidenceObject;mesh.visible=herodianPhaseActive()&&(!object||evidenceResolution.allows(object,mode))}for(const mesh of temporalMeshes.values())mesh.visible=mesh.userData.temporalActive&&evidenceAllowed(mesh.userData.evidenceLevel);if(renderer.shadowMap.enabled)renderer.shadowMap.needsUpdate=true;needsFrame=true}
 function setTemporalCityState(objects=[],position=0,phaseId=''){currentPhaseId=phaseId;applyTemporalState();const activeIds=new Set();objects.forEach((object,index)=>{if(!(object.visible||object.ruined))return;activeIds.add(object.id);let mesh=temporalMeshes.get(object.id);if(!mesh){const shape=temporalShape(object,index),geometry=new THREE.BoxGeometry(shape.w,shape.h,shape.d),level=temporalEvidence(object);mesh=new THREE.Mesh(geometry,temporalMaterials[level]);mesh.position.set(shape.x,shape.h/2,shape.z);mesh.rotation.y=shape.rotation;mesh.castShadow=renderer.shadowMap.enabled;mesh.receiveShadow=true;mesh.userData={temporalObject:object,evidenceLevel:level,baseHeight:shape.h,temporalActive:true};temporalMeshes.set(object.id,mesh);temporalLayer.add(mesh)}mesh.userData.temporalActive=true;mesh.userData.temporalObject=object;mesh.visible=evidenceAllowed(mesh.userData.evidenceLevel);const ruined=object.ruined;mesh.scale.y=ruined?.22:1;mesh.position.y=(mesh.userData.baseHeight*mesh.scale.y)/2-(ruined?10:0);mesh.rotation.z=ruined?.035:0;mesh.material.opacity=(mesh.userData.evidenceLevel==='disputed'?.5:.82)*(ruined?.52:1)});for(const[id,mesh]of temporalMeshes){if(!activeIds.has(id)){mesh.userData.temporalActive=false;mesh.visible=false}}temporalLayer.userData={position,phaseId,activeObjects:activeIds.size};if(renderer.shadowMap.enabled)renderer.shadowMap.needsUpdate=true;needsFrame=true}
 const ready=Promise.all([fetch('./data/objects/herodian-30ce.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`Herodian evidence ledger unavailable (${r.status})`);return r.json()}),loadTerrainAuthority()]).then(async([ledger,{manifest}])=>{if(!Array.isArray(ledger.objects)||!ledger.objects.length)throw new Error('Herodian evidence ledger empty');const evidenceResolutionAudit=auditEvidenceResolution(ledger.objects);evidenceResolution=new EvidenceResolutionEngine(ledger.objects);terrainRuntime=await loadCanonicalTerrain(manifest,root);if(!terrainRuntime)throw new Error('Canonical Jerusalem DEM payload missing: schematic terrain is prohibited after Step 3');const registrationAudit=auditSpatialRegistrations(ledger.objects,terrainRuntime);const architecturalGrammarAudit=auditArchitecturalGrammar(ledger.objects);if(architecturalGrammarAudit.eligible!==registrationAudit.rendered)throw new Error(`Grammar/registration mismatch: grammar=${architecturalGrammarAudit.eligible}, registration=${registrationAudit.rendered}`);const registrations=[],piecesBefore=builder.pieces;for(const object of ledger.objects){const meshStart=builder.meshes.length,registered=addEvidenceArchitecture(builder,object,terrainRuntime);if(registered){renderableObjects++;for(let i=meshStart;i<builder.meshes.length;i++)builder.meshes[i].userData.evidenceObject=object;registrations.push({id:object.id,east:registered.east,north:registered.north,up:registered.up,accuracy:registered.accuracy,evidence:evidenceResolution.levelFor(object)})}}if(renderableObjects!==registrationAudit.rendered)throw new Error(`Registration/build mismatch: audit=${registrationAudit.rendered}, build=${renderableObjects}`);const architecturalPieceAudit=auditArchitecturalPieceDensity(ledger.objects,piecesBefore,builder.pieces);builder.finish(historical);historical.visible=false;applyTemporalState();const info={renderableObjects,ledgerObjects:ledger.objects.length,constructionPieces:builder.pieces,assemblyRuntime:'HeritageBuilder/aBuild/uBuildProgress',transformationRuntime:'reversible-standing-to-ruin',temporalRuntime:'anchor-era-lifecycle-layer',evidenceResolution:evidenceResolution.summary(),evidenceResolutionAudit,terrain:'canonical-dem',terrainMin:terrainRuntime.min,terrainMax:terrainRuntime.max,spatialRegistration:'canonical-dem-enu',registrationAudit,architecturalGrammarAudit,architecturalPieceAudit,registrations,renderProfile:{pixelRatio,coarsePointer,reducedMotion,shadows:renderer.shadowMap.enabled}};onReady?.(info);return info});
 let needsFrame=true,lastNow=performance.now(),raf=0;controls.addEventListener('change',()=>needsFrame=true);const resize=()=>{const w=Math.max(1,mount.clientWidth),h=Math.max(1,mount.clientHeight);renderer.setSize(w,h,false);camera.aspect=w/h;camera.fov=camera.aspect<.58?39:34;camera.updateProjectionMatrix();needsFrame=true};const ro=new ResizeObserver(resize);ro.observe(mount);resize();function render(now){const dt=Math.min((now-lastNow)/1000,.1);lastNow=now;const changed=controls.update(dt);if(!document.hidden&&(needsFrame||changed||controls.autoRotate)){if(renderer.shadowMap.enabled)renderer.shadowMap.needsUpdate=true;renderer.render(scene,camera);needsFrame=false}raf=requestAnimationFrame(render)}raf=requestAnimationFrame(render);return{scene,camera,renderer,controls,root,ready,setBuildProgress,setRuinProgress,setEvidenceMode,setTemporalCityState,dispose(){cancelAnimationFrame(raf);ro.disconnect();controls.dispose();builder.dispose();terrainRuntime?.dispose?.();for(const mesh of temporalMeshes.values())mesh.geometry.dispose();Object.values(temporalMaterials).forEach(m=>m.dispose());Object.values(materials).forEach(m=>m.dispose());renderer.dispose();renderer.domElement.remove()}};
}
